import React from 'react';
import styles from './EducationBotSection.module.css'; // Có thể dùng chung hoặc tạo CSS riên
import sectionStyles from '../Sections.module.css';
const ProductsEdu = () => {
  const data = [
    { id: 1, name: "Python Cơ bản",desc: "Khóa học Python Cơ bản được thiết kế dành cho người mới bắt đầu, giúp học viên nắm vững nền tảng lập trình với Python thông qua các kiến thức từ cài đặt môi trường, cú pháp cơ bản, biến và kiểu dữ liệu, cấu trúc điều kiện, vòng lặp, hàm, xử lý file cho đến việc làm quen với thư viện hỗ trợ như pandas và matplotlib. Trong suốt khóa học, học viên sẽ được thực hành qua các mini project như game đoán số, quản lý danh bạ, vẽ biểu đồ thống kê và hoàn thành một dự án cuối khóa nhằm củng cố kỹ năng. Sau khi hoàn thành, học viên có thể tự tin viết chương trình Python cơ bản, xử lý dữ liệu, tự động hóa các tác vụ đơn giản và có nền tảng vững chắc để học nâng cao trong các lĩnh vực như Data Science, AI, Machine Learning hay Web Development.",time: "8 tuần", price: 2000000 },
    { id: 2, name: "Lập trình Web với Django",desc: "Khóa học Lập trình Web với Django được xây dựng nhằm giúp học viên nhanh chóng nắm vững kiến thức và kỹ năng cần thiết để phát triển ứng dụng web chuyên nghiệp bằng framework Django của Python. Nội dung khóa học bao gồm cài đặt và cấu hình môi trường, kiến trúc MVC/MVT trong Django, làm việc với URL, view, template, và ORM để quản lý cơ sở dữ liệu. Học viên sẽ thực hành xây dựng hệ thống đăng nhập/đăng ký, phân quyền người dùng, quản trị nội dung, cũng như tích hợp API và triển khai ứng dụng lên môi trường thực tế. Thông qua các dự án thực hành, học viên không chỉ học cách viết code sạch, tối ưu và bảo mật, mà còn có được trải nghiệm toàn diện từ việc thiết kế cơ sở dữ liệu, xây dựng giao diện, đến triển khai web hoàn chỉnh. Sau khi hoàn thành khóa học, học viên sẽ có khả năng tự xây dựng website động, sẵn sàng ứng dụng vào công việc hoặc phát triển sản phẩm cá nhân.",time: "12 tuần", price: 4500000 },
    { id: 3, name: "Machine Learning Cơ bản",desc: "Khóa học Machine Learning Cơ bản mang đến nền tảng vững chắc cho người mới bắt đầu tiếp cận trí tuệ nhân tạo, giúp học viên hiểu rõ khái niệm, quy trình và các thuật toán cơ bản trong học máy. Nội dung bao gồm tiền xử lý dữ liệu, chia tập huấn luyện/kiểm thử, các mô hình học có giám sát (hồi quy tuyến tính, hồi quy logistic, cây quyết định, KNN, SVM), học không giám sát (phân cụm K-means, PCA), cùng với đánh giá mô hình bằng các chỉ số phổ biến. Trong quá trình học, học viên sẽ thực hành bằng Python và thư viện như scikit-learn, đồng thời xây dựng các project nhỏ như dự đoán giá nhà hay phân loại văn bản. Sau khi hoàn thành, học viên có khả năng hiểu và áp dụng các thuật toán ML cơ bản, chuẩn bị nền tảng để bước tiếp vào các mảng nâng cao hơn như Deep Learning, AI ứng dụng, và Data Science.",time: "12 tuần", price: 5000000 },
    { id: 4, name: "Trí tuệ nhân tạo ứng dụng",desc: "Khóa học Trí tuệ nhân tạo ứng dụng tập trung vào việc đưa AI từ lý thuyết vào thực tiễn, giúp học viên nắm vững cách sử dụng các mô hình và công cụ AI trong những bài toán thực tế như xử lý ngôn ngữ tự nhiên (chatbot, phân tích cảm xúc), thị giác máy tính (nhận diện hình ảnh, phân loại đối tượng), và hệ thống gợi ý. Nội dung khóa học bao gồm tổng quan về AI, quy trình xây dựng ứng dụng AI, thực hành với các thư viện phổ biến như TensorFlow, PyTorch, OpenCV, Hugging Face, cũng như triển khai mô hình trên nền tảng web hoặc cloud. Học viên sẽ được tham gia dự án thực hành như xây dựng chatbot đơn giản, hệ thống gợi ý phim, hoặc ứng dụng nhận diện hình ảnh. Sau khóa học, học viên có thể thiết kế và triển khai các ứng dụng AI cơ bản, đồng thời có nền tảng để phát triển các dự án AI nâng cao trong nghiên cứu hoặc doanh nghiệp.",time: "14 tuần ", price: 6500000 },
    { id: 5, name: "Digital Marketing",desc: "Khóa học Digital Marketing được thiết kế để giúp học viên nắm vững kiến thức và kỹ năng tiếp thị số trong thời đại công nghệ, từ việc xây dựng chiến lược marketing tổng thể đến triển khai các kênh cụ thể như SEO, quảng cáo Google/Facebook, email marketing, content marketing và quản lý mạng xã hội. Nội dung khóa học kết hợp lý thuyết nền tảng với các case study thực tế, giúp học viên biết cách nghiên cứu thị trường, phân tích hành vi khách hàng, tối ưu ngân sách quảng cáo và đo lường hiệu quả chiến dịch bằng các công cụ như Google Analytics, Meta Business Suite hay các nền tảng CRM. Sau khi hoàn thành, học viên có khả năng tự xây dựng và quản lý chiến dịch Digital Marketing toàn diện, phục vụ cho kinh doanh cá nhân, doanh nghiệp hoặc phát triển sự nghiệp trong lĩnh vực marketing số.",time: "10 tuần", price: 4000000 },
    { id: 6, name: "Illustrator cho người mới",desc: "Khóa học Illustrator cho người mới được thiết kế dành cho những ai bắt đầu làm quen với thiết kế đồ họa vector, giúp học viên nắm vững các công cụ cơ bản trong Adobe Illustrator như tạo hình, vẽ vector, sử dụng màu sắc, quản lý layer và text. Nội dung khóa học tập trung vào việc thực hành qua các bài tập trực quan như thiết kế logo, icon, infographic và poster, từ đó rèn luyện khả năng sáng tạo và kỹ năng thiết kế chuyên nghiệp. Sau khi hoàn thành, học viên có thể tự tin sử dụng Illustrator để sáng tạo ấn phẩm đồ họa cho học tập, công việc truyền thông – marketing hoặc khởi đầu sự nghiệp trong lĩnh vực thiết kế.",time: "8 tuần", price: 3500000 },
    { id: 7, name: "UI/UX Design",desc: "Khóa học tập trung vào tư duy thiết kế trải nghiệm người dùng (UX) và giao diện trực quan (UI). Học viên học quy trình thiết kế sản phẩm số: nghiên cứu người dùng, xây dựng wireframe, thiết kế prototype bằng Figma/Adobe XD, kiểm thử và tối ưu trải nghiệm. Cuối khóa, học viên hoàn thiện một case study thiết kế app/web.",time: "10 tuần", price: 4500000 },
    { id: 8, name: "Tiếng Anh giao tiếp",desc: "Khóa học chú trọng vào nghe – nói thực hành, giúp học viên tự tin giao tiếp trong đời sống và công việc. Nội dung bao gồm phát âm chuẩn, mẫu câu thông dụng, hội thoại theo chủ đề (giới thiệu bản thân, phỏng vấn, du lịch, thuyết trình). Học viên được luyện phản xạ qua role-play và tương tác trực tiếp.",time: "12 tuần", price: 4000000 },
    { id: 9, name: "Quản trị dự án Agile",desc: "Khóa học giúp học viên hiểu và áp dụng các phương pháp quản trị dự án hiện đại như Agile và Scrum. Nội dung bao gồm lập kế hoạch sprint, quản lý backlog, daily meeting, tracking tiến độ và đánh giá kết quả. Học viên thực hành quản lý dự án nhóm nhỏ để hiểu rõ vai trò Scrum Master, Product Owner và Developer.",time: "8 tuần", price: 4500000 },
    { id: 10, name: "An toàn thông tin cơ bản",desc: "Khóa học giới thiệu những kiến thức nền tảng về bảo mật: các mối đe dọa mạng, cách hacker tấn công, phương pháp mã hóa cơ bản, quản lý mật khẩu và an toàn khi sử dụng Internet. Học viên sẽ biết cách phòng tránh rủi ro, bảo mật dữ liệu cá nhân và thiết lập hệ thống an toàn cho tổ chức.",time: "12 tuần", price: 5500000 },
    { id: 11, name: "Python Nâng cao",desc: "Khóa học Python Nâng cao dành cho những ai đã nắm vững kiến thức cơ bản và muốn phát triển kỹ năng lập trình lên tầm chuyên sâu hơn, tập trung vào các chủ đề quan trọng như lập trình hướng đối tượng (OOP), quản lý bộ nhớ, xử lý ngoại lệ nâng cao, làm việc với module và package, đồng thời làm quen với các thư viện mạnh mẽ trong phân tích dữ liệu, trực quan hóa, web scraping và tự động hóa. Học viên cũng sẽ được tiếp cận với kỹ thuật lập trình bất đồng bộ (async/await), testing, tối ưu hiệu năng và thực hành qua các dự án thực tế như xây dựng ứng dụng nhỏ, khai thác dữ liệu từ website, hoặc tạo công cụ phân tích dữ liệu. Sau khóa học, học viên có khả năng viết code Python chuyên nghiệp, tối ưu và dễ bảo trì, sẵn sàng ứng dụng vào công việc chuyên môn hoặc tiếp tục học các lĩnh vực nâng cao như trí tuệ nhân tạo, khoa học dữ liệu, và phát triển phần mềm quy mô lớn.",time: "10 tuần", price:3500000  },
    { id: 12, name: "Phân tích dữ liệu bằng R",desc: "Khóa học Phân tích dữ liệu bằng R được thiết kế cho những ai muốn làm chủ công cụ R trong xử lý và khai thác dữ liệu, từ những bước cơ bản như thao tác với dữ liệu, làm sạch, biến đổi, đến phân tích thống kê và trực quan hóa bằng các thư viện mạnh mẽ như ggplot2, dplyr và tidyr. Học viên sẽ được hướng dẫn thực hành trên các bộ dữ liệu thực tế, áp dụng các phương pháp thống kê mô tả, kiểm định giả thuyết, hồi quy, cũng như xây dựng báo cáo phân tích trực quan. Sau khi hoàn thành, học viên có thể tự tin sử dụng R để khai thác insight từ dữ liệu, hỗ trợ ra quyết định trong kinh doanh, nghiên cứu, hoặc tiếp tục học nâng cao trong các lĩnh vực như khoa học dữ liệu và machine learning.",time: "8 tuần", price: 3000000},
    { id: 13, name: "Thiết kế đồ họa Photoshop",desc: "Khóa học Thiết kế đồ họa Photoshop được xây dựng cho những ai muốn làm chủ công cụ Photoshop trong thiết kế và sáng tạo hình ảnh. Nội dung khóa học bao gồm làm quen giao diện và công cụ cơ bản, kỹ thuật chỉnh sửa ảnh, cắt ghép, blend màu, thiết kế banner, poster, ấn phẩm truyền thông và xây dựng bố cục chuyên nghiệp. Học viên sẽ được thực hành qua các bài tập thực tế như chỉnh sửa ảnh chân dung, thiết kế poster quảng cáo, banner online, từ đó rèn luyện mắt thẩm mỹ và kỹ năng sử dụng công cụ linh hoạt. Sau khi hoàn thành, học viên có thể tự tin thiết kế sản phẩm đồ họa phục vụ học tập, công việc hoặc khởi đầu sự nghiệp trong ngành thiết kế sáng tạo.",time: "8 tuần", price:3500000  },
    { id: 14, name: "Kỹ năng thuyết trình",desc: "Khóa học giúp học viên rèn luyện khả năng trình bày ý tưởng mạch lạc, cuốn hút và tự tin trước đám đông. Nội dung bao gồm cách xây dựng dàn ý, kỹ thuật mở đầu – kết thúc ấn tượng, ngôn ngữ cơ thể, quản lý giọng nói, và sử dụng công cụ trực quan như PowerPoint, Canva. Học viên sẽ được thực hành thuyết trình nhiều lần và nhận phản hồi trực tiếp để cải thiện.",time: "6 tuần", price: 2500000  },
    { id: 15, name: "Kỹ năng giao tiếp",desc: "Khóa học tập trung vào việc nâng cao kỹ năng lắng nghe, diễn đạt và thuyết phục trong cả môi trường công sở lẫn đời sống hàng ngày. Học viên được học cách đặt câu hỏi, quản lý cảm xúc, ứng xử trong tình huống khó, giao tiếp qua email/online và xây dựng mối quan hệ hiệu quả.",time: "6 tuần", price:2500000  },
    { id: 16, name: "Lập trình Web Frontend",desc: "Học viên được học nền tảng vững chắc về HTML, CSS, JavaScript, cùng các framework hiện đại như React hoặc Vue. Nội dung bao gồm thiết kế giao diện, responsive web, tối ưu tốc độ tải trang và tương tác người dùng. Cuối khóa, học viên sẽ hoàn thành project website hoàn chỉnh (ví dụ: trang portfolio hoặc landing page).",time: "12 tuần", price: 5000000 },
    { id: 17, name: "SQL và Cơ sở dữ liệu",desc: "Khóa học cung cấp kiến thức từ cơ bản đến nâng cao về SQL: tạo bảng, truy vấn dữ liệu, JOIN, GROUP BY, Subquery, Stored Procedure. Ngoài ra, học viên được thực hành trên MySQL hoặc PostgreSQL để phân tích dữ liệu, tối ưu truy vấn và thiết kế cơ sở dữ liệu chuẩn hóa cho ứng dụng.",time: "10 tuần", price: 3000000 },
    { id: 18, name: "Phát triển ứng dụng di động",desc: "Học viên sẽ học cách xây dựng ứng dụng di động native hoặc cross-platform (React Native/Flutter). Nội dung bao gồm thiết kế giao diện, kết nối API, quản lý dữ liệu (SQLite/Firebase), và triển khai ứng dụng lên App Store/Google Play. Cuối khóa, học viên có thể tự làm app ghi chú, chat đơn giản hoặc quản lý công việc.",time: "14 tuần", price: 6000000 },
    { id: 19, name: "Tiếng Nhật N5",desc: "Khóa học dành cho người mới, bắt đầu từ bảng chữ cái Hiragana, Katakana đến ngữ pháp, từ vựng, kanji cơ bản và mẫu hội thoại đơn giản. Học viên được rèn luyện kỹ năng nghe – nói – đọc – viết để đạt trình độ N5 trong kỳ thi JLPT. Cuối khóa có các bài test mô phỏng đề thi thật để củng cố kiến thức.",time: "16 tuần", price: 6000000 },
    { id: 20, name: "Điện toán đám mây",desc: "Khóa học cung cấp kiến thức về khái niệm cloud computing, các mô hình dịch vụ (IaaS, PaaS, SaaS) và ứng dụng trong doanh nghiệp. Học viên sẽ được thực hành trên AWS/Azure/GCP với các thao tác như tạo máy ảo, triển khai ứng dụng web, lưu trữ dữ liệu và bảo mật. Cuối khóa, học viên có thể tự triển khai một hệ thống web cơ bản lên cloud.",time: "10 tuần", price: 5000000 },
  ];

  return (
    <div className={styles.wrapper}>
      <h2 className={sectionStyles.word}>Danh Sách Khóa Học Tại Trung Tâm</h2>
      <h4>🌟Hãy tham khảo danh sách các khóa học dưới đây và thử hỏi nhân viên tư vấn, hoặc đăng ký khóa học bạn quan tâm nha!</h4>
      <table className={styles.table}>
        <thead>
          <tr>
            <th>Mã Khóa Học</th>
            <th>Khóa Học</th>
            <th>Mô tả nội dung</th> 
            <th>Thời gian khóa học</th>
            <th>Học phí</th>
          </tr>
        </thead>
        <tbody>
          {data.map((p) => (
            <tr key={p.id}>
              <td>{p.id}</td>
              <td>{p.name}</td>
              <td>{p.desc}</td>
              <td>{p.time}</td>
              <td>{p.price}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default ProductsEdu;