import React from 'react';
import styles from './EcommerceBotSection.module.css'; // Có thể dùng chung hoặc tạo CSS riên
import sectionStyles from '../Sections.module.css';
const Products = () => {
  const data = [
  { id: 1, name: "Cảm Biến Chuyển Động Wifi Thông Minh 6SHOME", price: 454000, variance: "KHÔNG kèm cốc sạc", description: "Chế Độ Báo Khách Cảm Biến Chống Trộm Điều Khiển Từ Xa Qua Điện Thoại" },
  { id: 2, name: "Cảm Biến Chuyển Động Wifi Thông Minh 6SHOME", price: 474000, variance: "KÈM cốc sạc", description: "Chế Độ Báo Khách Cảm Biến Chống Trộm Điều Khiển Từ Xa Qua Điện Thoại" },
  { id: 3, name: "Bóng Đèn Led Wifi Thông Minh Tuya 16 triệu màu", price: 338000, variance: "Bóng đèn 9W Tuya", description: "công suất 15W 9W điều khiển từ xa nháy theo nhạc" },
  { id: 4, name: "Bóng Đèn Led Wifi Thông Minh Tuya 16 triệu màu", price: 138000, variance: "Bóng đèn 9W 6SHOME", description: "công suất 15W 9W điều khiển từ xa nháy theo nhạc" },
  { id: 5, name: "Thiết Bị Điều Khiển Không Dây Aqara Cube T1/ T1 Pro", price: 490000, variance: "T1", description: "Điều Khiển Nhà Thông Minh Với 6 Cử Động: Đẩy Lắc Chạm Xoay Lật" },
  { id: 6, name: "Thiết Bị Điều Khiển Không Dây Aqara Cube T1/ T1 Pro", price: 599000, variance: "T1 Pro", description: "Điều Khiển Nhà Thông Minh Với 6 Cử Động: Đẩy Lắc Chạm Xoay Lật" },
  { id: 7, name: "Adapter Củ Sạc Dùng Cho Các Thiết Bị Thông Minh", price: 40000, variance: "", description: "Nguồn Cắm Cảm biến Thông Minh 5V-1A" },
  { id: 8, name: "Đèn Ốp Trần Aqara T1M Symphony Ceiling Light Zigbee", price: 3590000, variance: "", description: "Ánh Sáng 2700-6500K,16 Triệu Màu Hẹn Giờ Bật Tắt Trên Điện Thoại" },
  { id: 9, name: "CB Aptomat Wifi Thông Minh Cầu Dao Thông Minh 6SHOME Chống Dòng Rò Chống Giật 2P 63A", price: 658300, variance: "40A (C)", description: "Điều khiển Wifi Qua Điện Thoại" },
  { id: 10, name: "CB Aptomat Wifi Thông Minh Cầu Dao Thông Minh 6SHOME Chống Dòng Rò Chống Giật 2P 63A", price: 850000, variance: "2P 63A (B)", description: "Điều khiển Wifi Qua Điện Thoại" },
  { id: 11, name: "CB Aptomat Wifi Thông Minh Cầu Dao Thông Minh 6SHOME Chống Dòng Rò Chống Giật 2P 63A", price: 598500, variance: "2P63A có màn hình(A)", description: "Điều khiển Wifi Qua Điện Thoại" },
  { id: 12, name: "CB Aptomat Wifi Thông Minh Cầu Dao Thông Minh 6SHOME", price: 1160600, variance: "2P 63A", description: "Chống Dòng Rò Chống Giật 63A  Điều khiển Wifi Qua Điện Thoại" },
  { id: 13, name: "CB Aptomat Wifi Thông Minh Cầu Dao Thông Minh 6SHOME", price: 1043000, variance: "63A", description: "Chống Dòng Rò Chống Giật 63A  Điều khiển Wifi Qua Điện Thoại" },
  { id: 14, name: "CB Aptomat Wifi Thông Minh Cầu Dao Thông Minh 6SHOME", price: 1870400, variance: "2P 63A Bảo vệ rò rỉ", description: "Chống Dòng Rò Chống Giật 63A  Điều khiển Wifi Qua Điện Thoại" },
  { id: 15, name: "Apple TV 4K Gen 7 4K HDR 64GB", price: 3895000, variance: "Gen 6 64Gb", description: "Hub Trung Tâm Điều Khiển Nhà Thông Minh Lan/WiFi - Điều Khiển Từ Xa Tích Hợp Siri" },
  { id: 16, name: "Apple TV 4K Gen 7 4K HDR 128GB", price: 4590000, variance: "Gen 7 128Gb", description: "Hub Trung Tâm Điều Khiển Nhà Thông Minh Lan/WiFi - Điều Khiển Từ Xa Tích Hợp Siri" },
  { id: 17, name: "Thiết bị điều khiển từ xa 6SHOME", price: 270000, variance: "Wifi + RF433 trắng", description: "thông minh tiện lợi" },
  { id: 18, name: "Thiết bị điều khiển từ xa 6SHOME", price: 270000, variance: "Wifi + RF433 đen", description: "thông minh tiện lợi" },
  { id: 19, name: "Cảm Biến Đóng Mở Cửa Thông Minh Wifi 6SHOME", price: 204000, variance: "KÈM 2 Pin Energize", description: "Cảnh Báo Đột Nhập Tự Động Bật Đèn Điều Khiển trên Điện Thoại qua WiFi/4G" },
  { id: 20, name: "Cảm Biến Đóng Mở Cửa Thông Minh Wifi 6SHOME", price: 169000, variance: "KHÔNG kèm pin", description: "Cảnh Báo Đột Nhập Tự Động Bật Đèn Điều Khiển trên Điện Thoại qua WiFi/4G" },
  { id: 21, name: "Ổ Cắm Điện Thông Minh Hẹn Giờ Wifi Tuya 16A 6SHOME", price: 599000, variance: "Ổ cắm Wifi 4 Cổng", description: "Chức Năng Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Tiêu Thụ" },
  { id: 22, name: "Ổ Cắm Điện Thông Minh Hẹn Giờ Wifi Tuya 16A 6SHOME", price: 498000, variance: "Combo 2 Ổ Tuya", description: "Chức Năng Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Tiêu Thụ" },
  { id: 23, name: "Ổ Cắm Điện Thông Minh Hẹn Giờ Wifi Tuya 16A 6SHOME", price: 249000, variance: "Ổ cắm Tuya Tiếng Anh", description: "Chức Năng Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Tiêu Thụ" },
  { id: 24, name: "Ổ Cắm Điện Thông Minh Hẹn Giờ Wifi Tuya 16A 6SHOME", price: 747000, variance: "Combo 3 Ổ Tuya", description: "Chức Năng Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Tiêu Thụ" },
  { id: 25, name: "Ổ Cắm Điện Thông Minh Aqara", price: 790000, variance: "", description: "Điều Khiển Thiết Bị Từ Xa Hẹn Giờ Đo Điện Năng Tiêu Thụ Bản US" },
  { id: 26, name: "Bóng Đèn Thông Minh Yeelight W4 E27 Đui Xoắn RGB 9W", price: 390000, variance: "", description: "Hẹn Giờ Bật Tắt Từ Xa Điều Khiển Giọng Nói" },
  { id: 27, name: "Pin Energizer Max AAA E92 2A 1.5V", price: 65000, variance: "", description: "Dùng Cho Thiết Bị Thông Minh Chính Hãng" },
  { id: 28, name: "Thiết Bị Chống Trộm Báo Khách WiFi Hunonic CT01", price: 279000, variance: "Còi Báo Động", description: "App Tiếng Việt Phát Hiện Chuyển Động Còi Hú Cảnh Báo Qua Điện Thoại" },
  { id: 29, name: "Thiết Bị Chống Trộm Báo Khách WiFi Hunonic CT01", price: 999000, variance: "Combo 2 Vị Trí", description: "App Tiếng Việt Phát Hiện Chuyển Động Còi Hú Cảnh Báo Qua Điện Thoại" },
  { id: 30, name: "Thiết Bị Chống Trộm Báo Khách WiFi Hunonic CT01", price: 550000, variance: "Thiết bị Chống Trộm", description: "App Tiếng Việt Phát Hiện Chuyển Động Còi Hú Cảnh Báo Qua Điện Thoại" },
  { id: 31, name: "Thiết Bị Chống Trộm Báo Khách WiFi Hunonic CT01", price: 650000, variance: "Thiết bị + Còi báo", description: "App Tiếng Việt Phát Hiện Chuyển Động Còi Hú Cảnh Báo Qua Điện Thoại" },
  { id: 32, name: "Bộ Điều Khiển Hồng Ngoại WIFI IR Thông Minh 6SHOME", price: 456000, variance: "S09 IR CÓ MÀN HÌNH", description: "Điều Khiển Máy Lạnh Quạt Tivi,... Đo Nhiệt Độ Độ Ẩm Có Màn Hình" },
  { id: 33, name: "Bộ Điều Khiển Hồng Ngoại WIFI IR Thông Minh 6SHOME", price: 264600, variance: "S06", description: "Điều Khiển Máy Lạnh Quạt Tivi,... Đo Nhiệt Độ Độ Ẩm Có Màn Hình" },
  { id: 34, name: "Bộ Điều Khiển Hồng Ngoại WIFI IR Thông Minh 6SHOME", price: 230000, variance: "S08", description: "Điều Khiển Máy Lạnh Quạt Tivi,... Đo Nhiệt Độ Độ Ẩm Có Màn Hình" },
  { id: 35, name: "Bộ Điều Khiển Hồng Ngoại WIFI IR Thông Minh 6SHOME", price: 312000, variance: "S11 IR+RF", description: "Điều Khiển Máy Lạnh Quạt Tivi,... Đo Nhiệt Độ Độ Ẩm Có Màn Hình" },
  { id: 36, name: "Camera Thông Minh Tuya 4MP 2K Wifi 2.4/5GHz Trong Nhà", price: 1297000, variance: "Kèm Thẻ Nhớ Lexar32G", description: "An Ninh Hiện Đại Chất Lượng Ảnh Siêu Nét" },
  { id: 37, name: "Camera Thông Minh Tuya 4MP 2K Wifi 2.4/5GHz Trong Nhà", price: 1188600, variance: "Không Kèm Thẻ Nhớ", description: "An Ninh Hiện Đại Chất Lượng Ảnh Siêu Nét" },
  { id: 38, name: "Camera Thông Minh Tuya 4MP 2K Wifi 2.4/5GHz Trong Nhà", price: 1347000, variance: "Kèm Thẻ Nhớ Lexar64G", description: "An Ninh Hiện Đại Chất Lượng Ảnh Siêu Nét" },
  { id: 39, name: "Công Tắc Thông Minh Bình Nóng Lạnh Wifi/4G Công Suất Cao 6SHOME 20A - 4400W", price: 417000, variance: "Trắng", description: "Hẹn Giờ Điều Khiển Từ Xa Qua Điện Thoại" },
  { id: 40, name: "Công Tắc Thông Minh Bình Nóng Lạnh Wifi/4G Công Suất Cao 6SHOME 20A - 4400W", price: 417000, variance: "Đen", description: "Hẹn Giờ Điều Khiển Từ Xa Qua Điện Thoại" },
  { id: 41, name: "Ổ Cắm Điện Âm Tường Chữ Nhật Mặt Kính Cường Lực Viền Vàng", price: 372100, variance: "Đen", description: "Đa Năng và Hỗ Trợ Nối Đất" },
  { id: 42, name: "Ổ Cắm Điện Âm Tường Chữ Nhật Mặt Kính Cường Lực Viền Vàng", price: 308200, variance: "Trắng", description: "Đa Năng và Hỗ Trợ Nối Đất" },
  { id: 43, name: "Cảm Biến Ánh Sáng Thông Minh Wifi 6SHOME", price: 456000, variance: "", description: "Kết Hợp Tự Động Bật Đèn khi Tối Tự Động Đóng Rèm khi Nắng App Tuya SmartLife" },
  { id: 44, name: "Khóa Cửa Thông Minh Aqara U100", price: 5990000, variance: "", description: "Tích Hợp Vân Tay Khoá An Toàn Chống Nước Hỗ Trợ HomeKey/HomeKit" },
  { id: 45, name: "Ổ Cắm Điện Đôi Âm Tường Full Mặt Kính Cường Lực 16A", price: 239000, variance: "Đen", description: "Phù Hợp Mọi Chân Cắm Đồng Bộ Công Tắc TUYA" },
  { id: 46, name: "Ổ Cắm Điện Đôi Âm Tường Full Mặt Kính Cường Lực 16A", price: 239000, variance: "Trắng", description: "Phù Hợp Mọi Chân Cắm Đồng Bộ Công Tắc TUYA" },
  { id: 47, name: "Đui Đèn Thông Minh WiFi Hunonic 500W", price: 350000, variance: "Đui Đèn", description: "App Tiếng Việt Điều Khiển Từ Xa Trên Điện Thoại Hẹn Giờ Điều Khiển Giọng Nói" },
  { id: 48, name: "Đui Đèn Thông Minh WiFi Hunonic 500W", price: 390000, variance: "Combo Đui + Bóng Đèn", description: "App Tiếng Việt Điều Khiển Từ Xa Trên Điện Thoại Hẹn Giờ Điều Khiển Giọng Nói" },
  { id: 49, name: "Bộ Điều Khiển Trung Tâm Aqara Hub E1 USB Zigbee Extender", price: 1590000, variance: "Aqara Hub M2", description: "Mở Rộng Sóng Zigbee/WiFi Bản Quốc Tế" },
  { id: 50, name: "Bộ Điều Khiển Trung Tâm Aqara Hub E1 USB Zigbee Extender", price: 990000, variance: "Aqara Hub E1 USB", description: "Mở Rộng Sóng Zigbee/WiFi Bản Quốc Tế" },
  { id: 51, name: "Bộ Điều Khiển Trung Tâm Aqara Hub E1 USB Zigbee Extender", price: 1690000, variance: "Aqara Hub M1S Gen 2", description: "Mở Rộng Sóng Zigbee/WiFi Bản Quốc Tế" },
  { id: 52, name: "Máy Cho Thú Cưng Ăn Tự Động Aqara C1 Zigbee", price: 2789000, variance: "", description: "Điều Khiển Từ Xa Hẹn Lịch Trình Thép Không Gỉ Cao Cấp Khoá An Toàn" },
  { id: 53, name: "Bóng Đèn Thông Minh Yeelight Đui Cài RGB GU10 WiFi", price: 199000, variance: "Lẻ 1 Bóng không hộp", description: "Set 4 bóng RGB 16 Triệu Màu Điều Khiển Từ Xa Tiết Kiệm Điện" },
  { id: 54, name: "Bóng Đèn Thông Minh Yeelight Đui Cài RGB GU10 WiFi", price: 499000, variance: "Set 4 Bóng Full Box", description: "Set 4 bóng RGB 16 Triệu Màu Điều Khiển Từ Xa Tiết Kiệm Điện" },
  { id: 55, name: "Đèn Led Thanh Cảm Biến Dán Tủ Yeelight Mate Vỏ Bạc Ánh Sáng Dạng Chùm", price: 630000, variance: "Thanh 60cm", description: "Tích Hợp Pin Sạc Tự Động Tắt Khi Không Có Người" },
  { id: 56, name: "Đèn Led Thanh Cảm Biến Dán Tủ Yeelight Mate Vỏ Bạc Ánh Sáng Dạng Chùm", price: 505000, variance: "Thanh 42cm", description: "Tích Hợp Pin Sạc Tự Động Tắt Khi Không Có Người" },
  { id: 57, name: "Đèn Led Thanh Cảm Biến Dán Tủ Yeelight Mate Vỏ Bạc Ánh Sáng Dạng Chùm", price: 405000, variance: "Thanh 28cm", description: "Tích Hợp Pin Sạc Tự Động Tắt Khi Không Có Người" },
  { id: 58, name: "Cảm Biến Nhiệt Độ Độ Ẩm Aqara WSDCGQ11LM", price: 419000, variance: "", description: "Theo Dõi Môi Trường Bảo Vệ Sức Khoẻ Gia Đình Bản Quốc Tế" },
  { id: 59, name: "Cảm Biến Rung Aqara", price: 490000, variance: "", description: "Phát Hiện Rung Động Báo Qua Điện Thoại Bảo Vệ Nhà Cửa Pin 2 Năm Bản Quốc Tế Chính Hãng" },
  { id: 60, name: "Khóa Cửa Thông Minh Aqara D100 Zigbee/Bluetooth", price: 12899000, variance: "", description: "Khóa Vân Tay Lõi C Bảo Mật Cao Tích Hợp Nút Chuông Cửa Hỗ Trợ HomeKit" },
  { id: 61, name: "Đèn Gương Cầm Tay Đa Năng Yeelight 4 trong 1", price: 530000, variance: "", description: "Gương Đèn Sưởi tay Sạc dự phòng - Nhỏ Gọn Tiện Lợi" },
  { id: 62, name: "Đèn Ngủ Cảm Biến Chuyển Động Tích Điện Yeelight Treo/Dán", price: 325000, variance: "", description: "Tự Động Bật Tắt Chip LED Cao Cấp Pin 2 Tháng Tiết Kiệm Điện" },
  { id: 63, name: "Đèn Âm Trần Thông Minh Aqara T2 Downlight/Spotlight Zigbee Cao Cấp", price: 1190000, variance: "15°", description: "Điều Chỉnh Độ Sáng Điều Khiển Qua Điện Thoại" },
  { id: 64, name: "Đèn Âm Trần Thông Minh Aqara T2 Downlight/Spotlight Zigbee Cao Cấp", price: 1190000, variance: "60°", description: "Điều Chỉnh Độ Sáng Điều Khiển Qua Điện Thoại" },
  { id: 65, name: "Đèn Âm Trần Thông Minh Aqara T2 Downlight/Spotlight Zigbee Cao Cấp", price: 1190000, variance: "36°", description: "Điều Chỉnh Độ Sáng Điều Khiển Qua Điện Thoại" },
  { id: 66, name: "Đèn Âm Trần Thông Minh Aqara T2 Downlight/Spotlight Zigbee Cao Cấp", price: 1190000, variance: "24°", description: "Điều Chỉnh Độ Sáng Điều Khiển Qua Điện Thoại" },
  { id: 67, name: "Bộ Hồng Ngoại Hunonic IR Smart Pro", price: 389000, variance: "IR Tiêu Chuẩn", description: "Điều Khiển Hẹn Giờ Tivi Điều Hoà Từ Xa Qua Điện Thoại Tiết Kiệm Điện" },
  { id: 68, name: "Bộ Hồng Ngoại Hunonic IR Smart Pro", price: 615000, variance: "IR Pro + Sạc", description: "Điều Khiển Hẹn Giờ Tivi Điều Hoà Từ Xa Qua Điện Thoại Tiết Kiệm Điện" },
  { id: 69, name: "Bộ Hồng Ngoại Hunonic IR Smart Pro", price: 585000, variance: "IR Pro", description: "Điều Khiển Hẹn Giờ Tivi Điều Hoà Từ Xa Qua Điện Thoại Tiết Kiệm Điện" },
  { id: 70, name: "Bộ Hồng Ngoại Hunonic IR Smart Pro", price: 409000, variance: "IR Tiêu Chuẩn + Sạc", description: "Điều Khiển Hẹn Giờ Tivi Điều Hoà Từ Xa Qua Điện Thoại Tiết Kiệm Điện" },
  { id: 71, name: "Dao Rọc Giấy Dao Đa Năng Có Khe Bẻ Lưỡi W0455 WYNN'S TOOLS", price: 18000, variance: "", description: "Chốt Khoá An Toàn Đóng Hàng Khui Hàng Tiện Lợi" },
  { id: 72, name: "Cảm Biến Gắn Cửa Wifi Thông Minh Tuya", price: 446000, variance: "", description: "Loa Báo Động Chống Trộm - Bảo Vệ An Ninh Gia Đình" },
  { id: 73, name: "Camera AI Hanet Home HA800", price: 3059000, variance: "Kèm Thẻ Sandisk 64G", description: "360 Độ Nhận Diện Khuôn Mặt Video 2K Đàm Thoại 2 Chiều" },
  { id: 74, name: "Camera AI Hanet Home HA800", price: 2899000, variance: "Không Kèm Thẻ Nhớ", description: "360 Độ Nhận Diện Khuôn Mặt Video 2K Đàm Thoại 2 Chiều" },
  { id: 75, name: "Camera AI Hanet Home HA800", price: 3009000, variance: "Kèm Thẻ Sandisk 32G", description: "360 Độ Nhận Diện Khuôn Mặt Video 2K Đàm Thoại 2 Chiều" },
  { id: 76, name: "Cảm Biến Chất Lượng Không Khí Aqara TVOC Air Quality Monitor Zigbee 3.0", price: 1290000, variance: "", description: "Đo TVOC Nhiệt Độ Độ Ẩm Cảnh Báo Ô Nhiễm" },
  { id: 77, name: "Mặt Công Tắc Thay Thế Công Tắc Aqara D1 Đa Dạng Màu Sắc", price: 400000, variance: "Màu Vàng,3 Nút", description: "Nhựa Cao Cấp Chống Tia UV Bền Màu Hàng Chính Hãng" },
  { id: 78, name: "Mặt Công Tắc Thay Thế Công Tắc Aqara D1 Đa Dạng Màu Sắc", price: 340000, variance: "Màu Xám,2 Nút", description: "Nhựa Cao Cấp Chống Tia UV Bền Màu Hàng Chính Hãng" },
  { id: 79, name: "Mặt Công Tắc Thay Thế Công Tắc Aqara D1 Đa Dạng Màu Sắc", price: 340000, variance: "Màu Vàng,2 Nút", description: "Nhựa Cao Cấp Chống Tia UV Bền Màu Hàng Chính Hãng" },
  { id: 80, name: "Mặt Công Tắc Thay Thế Công Tắc Aqara D1 Đa Dạng Màu Sắc", price: 400000, variance: "Màu Xám,3 Nút", description: "Nhựa Cao Cấp Chống Tia UV Bền Màu Hàng Chính Hãng" },
  { id: 81, name: "Mặt Công Tắc Thay Thế Công Tắc Aqara D1 Đa Dạng Màu Sắc", price: 290000, variance: "Màu Xám,1 Nút", description: "Nhựa Cao Cấp Chống Tia UV Bền Màu Hàng Chính Hãng" },
  { id: 82, name: "Mặt Công Tắc Thay Thế Công Tắc Aqara D1 Đa Dạng Màu Sắc", price: 290000, variance: "Màu Vàng,1 Nút", description: "Nhựa Cao Cấp Chống Tia UV Bền Màu Hàng Chính Hãng" },
  { id: 83, name: "Đèn Ốp Trần Thông Minh Aqara LED Ceiling Light L1-350 Zigbee", price: 1490000, variance: "", description: "Ánh Sáng Đa Màu Điều Khiển Từ Xa Tương Thích HomeKit" },
  { id: 84, name: "Ổ Cắm Thông Minh Aqara Chuẩn E.U 10A 2300W Zigbee 3.0", price: 890000, variance: "", description: "Điều Khiển Qua Điện Thoại Đo Điện Tương Thích Home Kit" },
  { id: 85, name: "Tua Vít Đa Năng Nhỏ 2 Đầu Trợ Lực Đảo Chiều", price: 39000, variance: "", description: "Tô Vít Lùn Chính Hãng TOUSEN" },
  { id: 86, name: "Ổ Cắm Dài Thông Minh Wifi Tuya SmartLife 4 Cổng Độc Lập 4 USB", price: 673000, variance: "4Cổng4USB+Đầu Chuyển", description: "Điều Khiển Từ Xa Bật Tắt Từng Ổ" },
  { id: 87, name: "Camera Giám Sát TP-Link Tapo C211 2K 3MP", price: 899000, variance: "", description: "Tầm Nhìn Đêm Phát Hiện Chuyển Động Đàm Thoại 2 Chiều Điều Khiển Giọng Nói" },
  { id: 88, name: "Thẻ Nhớ MicroSD Lexar Ultra 32GB/64GB", price: 119000, variance: "32GB", description: "Tốc Độ 100MB/s Dùng Điện Thoại Camera Chính Hãng - BH 5 Năm" },
  { id: 89, name: "Thẻ Nhớ MicroSD Lexar Ultra 32GB/64GB", price: 179000, variance: "64GB", description: "Tốc Độ 100MB/s Dùng Điện Thoại Camera Chính Hãng - BH 5 Năm" },
  { id: 90, name: "Ổ Cắm Điện Tam Giác Đa Năng HADO", price: 240000, variance: "Ổ Cắm USB-2M", description: "10 Ổ Cắm 3 USB 1 Sạc Type C - Chịu Tải 3000W An Toàn Đa Năng Nhựa PC Cao Cấp" },
  { id: 91, name: "Ổ Cắm Điện Tam Giác Đa Năng HADO", price: 389000, variance: "D15- 10 Ổ- 3 USB- 4M", description: "10 Ổ Cắm 3 USB 1 Sạc Type C - Chịu Tải 3000W An Toàn Đa Năng Nhựa PC Cao Cấp" },
  { id: 92, name: "Ổ Cắm Điện Tam Giác Đa Năng HADO", price: 349000, variance: "D15- 10 Ổ- 3 USB- 2M", description: "10 Ổ Cắm 3 USB 1 Sạc Type C - Chịu Tải 3000W An Toàn Đa Năng Nhựa PC Cao Cấp" },
  { id: 93, name: "Ổ Cắm Điện Tam Giác Đa Năng HADO", price: 339000, variance: "D14- 8 Ổ- 3 USB- 2M", description: "10 Ổ Cắm 3 USB 1 Sạc Type C - Chịu Tải 3000W An Toàn Đa Năng Nhựa PC Cao Cấp" },
  { id: 94, name: "Ổ Cắm Điện Tam Giác Đa Năng HADO", price: 389000, variance: "D14- 8 Ổ- 3 USB- 4M", description: "10 Ổ Cắm 3 USB 1 Sạc Type C - Chịu Tải 3000W An Toàn Đa Năng Nhựa PC Cao Cấp" },
  { id: 95, name: "Ổ Cắm Điện Tam Giác Đa Năng HADO", price: 279000, variance: "T14 - 3 Ổ- 3 USB- 4M", description: "10 Ổ Cắm 3 USB 1 Sạc Type C - Chịu Tải 3000W An Toàn Đa Năng Nhựa PC Cao Cấp" },
  { id: 96, name: "Ổ Cắm Điện Tam Giác Đa Năng HADO", price: 219000, variance: "T14 - 3 Ổ- 3 USB- 2M", description: "10 Ổ Cắm 3 USB 1 Sạc Type C - Chịu Tải 3000W An Toàn Đa Năng Nhựa PC Cao Cấp" },
  { id: 97, name: "Đèn Ốp Trần Cảm Biến 250 Yeelight Mini", price: 660000, variance: "", description: "Tích Hợp Cảm Biến Nhiệt Độ Ánh Sáng Tiết Kiệm Điện Thiết Kế Chống Côn Trùng" },
  { id: 98, name: "Bộ Điều Khiển Trung Tâm Nhà Thông Minh Zigbee Tuya", price: 1319000, variance: "Hub HomeKit Zemi", description: "Zemismart Tương Thích Apple Homekit" },
  { id: 99, name: "Bộ Điều Khiển Trung Tâm Nhà Thông Minh Zigbee Tuya", price: 879000, variance: "Zigbee 3.0 LAN", description: "Zemismart Tương Thích Apple Homekit" },
  { id: 100, name: "Công Tắc Cảm Ứng Thông Minh Tuya Zigbee 3.0 Viền Vàng 2,3,4 Nút Chữ Nhật", price: 586000, variance: "Trắng,4 nút", description: "Điều Khiển Từ Xa Hẹn Giờ Ra Lệnh Giọng Nói" },
  { id: 101, name: "Công Tắc Cảm Ứng Thông Minh Tuya Zigbee 3.0 Viền Vàng 2,3,4 Nút Chữ Nhật", price: 574600, variance: "Đen,3 nút", description: "Điều Khiển Từ Xa Hẹn Giờ Ra Lệnh Giọng Nói" },
  { id: 102, name: "Công Tắc Cảm Ứng Thông Minh Tuya Zigbee 3.0 Viền Vàng 2,3,4 Nút Chữ Nhật", price: 557700, variance: "Đen,2 nút", description: "Điều Khiển Từ Xa Hẹn Giờ Ra Lệnh Giọng Nói" },
  { id: 103, name: "Công Tắc Cảm Ứng Thông Minh Tuya Zigbee 3.0 Viền Vàng 2,3,4 Nút Chữ Nhật", price: 574600, variance: "Trắng,3 nút", description: "Điều Khiển Từ Xa Hẹn Giờ Ra Lệnh Giọng Nói" },
  { id: 104, name: "Công Tắc Cảm Ứng Thông Minh Tuya Zigbee 3.0 Viền Vàng 2,3,4 Nút Chữ Nhật", price: 557700, variance: "Trắng,2 nút", description: "Điều Khiển Từ Xa Hẹn Giờ Ra Lệnh Giọng Nói" },
  { id: 105, name: "Công Tắc Cảm Ứng Thông Minh Tuya Zigbee 3.0 Viền Vàng 2,3,4 Nút Chữ Nhật", price: 586000, variance: "Đen,4 nút", description: "Điều Khiển Từ Xa Hẹn Giờ Ra Lệnh Giọng Nói" },
  { id: 106, name: "Bút Thử Điện Total AC 100-500V Total 4X140mm", price: 28000, variance: "", description: "An Toàn Chính Hãng Nhựa Bền Chắc THT291408" },
  { id: 107, name: "Công Tắc Âm Tường Thông Minh Aqara 1-2-3 Nút D1 Zigbee", price: 909000, variance: "1 Nút,KHÔNG dây nguội", description: "Tích Hợp Cảm Biến Nhiệt Độ Hẹn Giờ Từ Xa Bản Nội Địa" },
  { id: 108, name: "Công Tắc Âm Tường Thông Minh Aqara 1-2-3 Nút D1 Zigbee", price: 1090000, variance: "2 Nút,KHÔNG dây nguội", description: "Tích Hợp Cảm Biến Nhiệt Độ Hẹn Giờ Từ Xa Bản Nội Địa" },
  { id: 109, name: "Công Tắc Âm Tường Thông Minh Aqara 1-2-3 Nút D1 Zigbee", price: 969000, variance: "2 Nút,CÓ dây nguội", description: "Tích Hợp Cảm Biến Nhiệt Độ Hẹn Giờ Từ Xa Bản Nội Địa" },
  { id: 110, name: "Công Tắc Âm Tường Thông Minh Aqara 1-2-3 Nút D1 Zigbee", price: 1190000, variance: "3 Nút,KHÔNG dây nguội", description: "Tích Hợp Cảm Biến Nhiệt Độ Hẹn Giờ Từ Xa Bản Nội Địa" },
  { id: 111, name: "Công Tắc Âm Tường Thông Minh Aqara 1-2-3 Nút D1 Zigbee", price: 869000, variance: "1 Nút,CÓ dây nguội", description: "Tích Hợp Cảm Biến Nhiệt Độ Hẹn Giờ Từ Xa Bản Nội Địa" },
  { id: 112, name: "Công Tắc Âm Tường Thông Minh Aqara 1-2-3 Nút D1 Zigbee", price: 1009000, variance: "3 Nút,CÓ dây nguội", description: "Tích Hợp Cảm Biến Nhiệt Độ Hẹn Giờ Từ Xa Bản Nội Địa" },
  { id: 113, name: "Module Điều Khiển LED Dây Aqara Strip Driver Zigbee", price: 790000, variance: "", description: "Chế độ RGBW Tương Thích HomeKit" },
  { id: 114, name: "Bóng Đèn Buld E27 NNC 30W MQ30BNNC", price: 68000, variance: "NNC 30W", description: "Ánh Sáng Dịu Trắng Vàng - Siêu Tiết Kiệm Điện Bảo Vệ Mắt Tuổi Thọ Cao" },
  { id: 115, name: "Bóng Đèn Buld E27 NNC 30W MQ30BNNC", price: 55600, variance: "MQ 20W", description: "Ánh Sáng Dịu Trắng Vàng - Siêu Tiết Kiệm Điện Bảo Vệ Mắt Tuổi Thọ Cao" },
  { id: 116, name: "Bóng Đèn Buld E27 NNC 30W MQ30BNNC", price: 82600, variance: "NNC 40W", description: "Ánh Sáng Dịu Trắng Vàng - Siêu Tiết Kiệm Điện Bảo Vệ Mắt Tuổi Thọ Cao" },
  { id: 117, name: "Bóng Đèn Buld E27 NNC 30W MQ30BNNC", price: 97000, variance: "MQ 50W", description: "Ánh Sáng Dịu Trắng Vàng - Siêu Tiết Kiệm Điện Bảo Vệ Mắt Tuổi Thọ Cao" },
  { id: 118, name: "Camera An Ninh Ngoài Trời IMOU Cruiser Z 5MP 12X", price: 2790000, variance: "", description: "Phát Hiện Người Chống Bụi Chống Nước IP66 Màu Ban Đêm Tích Hợp Còi" },
  { id: 119, name: "Công Tắc Cảm Ứng Vẫy Tay Tiệm Cận Hồng Ngoại WiFi Tuya 10A 220V", price: 429700, variance: "", description: "Điều Khiển Qua App Không Cần Chạm" },
  { id: 120, name: "Màn Hình Công Tắc Thông Minh Aqara Magic Switch S1E bản Quốc Tế", price: 2351700, variance: "", description: "Kết Nối Wifi Tương Thích HomeKit Alexa Google Assis" },
  { id: 121, name: "Khóa Cửa Thông Minh Aqara A100 Zigbee", price: 5990000, variance: "", description: "Mở Khoá Vân Tay Mở Qua Điện Thoại Chống Trộm Hoạt Động Độc Lập Bản Quốc Tế" },
  { id: 122, name: "Công Tắc Lahu 1 Kênh Công Suất Lớn Hunonic WiFi 4000W", price: 489000, variance: "Lahu 1 Kênh", description: "Hẹn Giờ Bật Tắt Từ Xa Hoạt Động Độc Lập App Tiếng Việt" },
  { id: 123, name: "Công Tắc Lahu 1 Kênh Công Suất Lớn Hunonic WiFi 4000W", price: 819000, variance: "Lahu 4 RTC", description: "Hẹn Giờ Bật Tắt Từ Xa Hoạt Động Độc Lập App Tiếng Việt" },
  { id: 124, name: "Công Tắc Lahu 1 Kênh Công Suất Lớn Hunonic WiFi 4000W", price: 539000, variance: "Lahu 4 Kênh", description: "Hẹn Giờ Bật Tắt Từ Xa Hoạt Động Độc Lập App Tiếng Việt" },
  { id: 125, name: "Công Tắc Lahu 1 Kênh Công Suất Lớn Hunonic WiFi 4000W", price: 409000, variance: "Lahu 2 Kênh", description: "Hẹn Giờ Bật Tắt Từ Xa Hoạt Động Độc Lập App Tiếng Việt" },
  { id: 126, name: "Công Tắc Lahu 1 Kênh Công Suất Lớn Hunonic WiFi 4000W", price: 989000, variance: "Noma 4CH", description: "Hẹn Giờ Bật Tắt Từ Xa Hoạt Động Độc Lập App Tiếng Việt" },
  { id: 127, name: "Thẻ Từ Aqara NFC", price: 199000, variance: "", description: "Dùng Để Mở Khóa Thông Minh Aqara D100 A100 D200i - Nhỏ Gọn Bảo Mật Cao Chống Sao Chép" },
  { id: 128, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 499000, variance: "Đen,Xanh Dương", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 129, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 499000, variance: "Trắng,Trắng", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 130, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 499000, variance: "Trắng,Đen", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 131, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 499000, variance: "Đen,Đỏ", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 132, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 499000, variance: "Trắng,Xanh Dương", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 133, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 499000, variance: "Đen,Đen", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 134, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 490000, variance: "Đen,Không Kèm Vỏ", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 135, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 499000, variance: "Đen,Trắng", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 136, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 490000, variance: "Trắng,Không Kèm Vỏ", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 137, name: "Định Vị Mapro Tag Âm Thanh 70dB Pin 1 Năm", price: 499000, variance: "Trắng,Đỏ", description: "Định Vị Vị Trí Trẻ Em Thú Cưng Đồ Đạc Ô Tô Xe Máy Chống Nước App FindMy" },
  { id: 138, name: "Cảm Biến Cửa Zigbee Tuya Pin AAA", price: 379500, variance: "", description: "Thời Lượng Pin 2 Năm Tương Thích Google Home & Amazon Alexa Báo Động An Ninh Gia Đình" },
  { id: 139, name: "Thanh Đèn LED RGB Nháy Theo Nhạc", price: 175000, variance: "Màu Đen + Sạc", description: "Cảm Ứng Âm Thanh Siêu Nhạy Trang Trí Bàn Làm Việc & Phòng" },
  { id: 140, name: "Thanh Đèn LED RGB Nháy Theo Nhạc", price: 175000, variance: "Màu Trắng + Sạc", description: "Cảm Ứng Âm Thanh Siêu Nhạy Trang Trí Bàn Làm Việc & Phòng" },
  { id: 141, name: "Thanh Đèn LED RGB Nháy Theo Nhạc", price: 155000, variance: "Màu Trắng", description: "Cảm Ứng Âm Thanh Siêu Nhạy Trang Trí Bàn Làm Việc & Phòng" },
  { id: 142, name: "Thanh Đèn LED RGB Nháy Theo Nhạc", price: 155000, variance: "Màu Đen", description: "Cảm Ứng Âm Thanh Siêu Nhạy Trang Trí Bàn Làm Việc & Phòng" },
  { id: 143, name: "Khoá Cửa Thông Minh Aqara D200i Facial Recognition Door Lock", price: 16990000, variance: "", description: "Face ID Nhận Diện Chính Xác Cảnh Báo Chống Trộm" },
  { id: 144, name: "Đèn Bàn Học Kiêm Đèn Pin Đa Năng Tích Điện Yeelight Mate", price: 630000, variance: "", description: "3 Chế Độ Chiếu Sáng Đa Năng Xoay Linh Hoạt Pin 1200mAh" },
  { id: 145, name: "Ổ Cắm Dài Thông Minh WiFi Tuya 4 Chấu 2 cổng USB", price: 680000, variance: "4 Cổng 2 USB", description: "Điều Khiển Độc Lập Từng Ổ Điều Khiển Hẹn Giờ Bật Tắt Từ Xa An Toàn" },
  { id: 146, name: "Công Tắc Âm Tường Thông Minh Aqara Z1 Pro 1-2-3-4 Nút 16A 2200W Zigbee 3.0", price: 1450000, variance: "3 Phím", description: "Điều Khiển Từ Xa Tương Thích Homekit" },
  { id: 147, name: "Công Tắc Âm Tường Thông Minh Aqara Z1 Pro 1-2-3-4 Nút 16A 2200W Zigbee 3.0", price: 1550000, variance: "4 Phím", description: "Điều Khiển Từ Xa Tương Thích Homekit" },
  { id: 148, name: "Công Tắc Âm Tường Thông Minh Aqara Z1 Pro 1-2-3-4 Nút 16A 2200W Zigbee 3.0", price: 1250000, variance: "1 Phím", description: "Điều Khiển Từ Xa Tương Thích Homekit" },
  { id: 149, name: "Công Tắc Âm Tường Thông Minh Aqara Z1 Pro 1-2-3-4 Nút 16A 2200W Zigbee 3.0", price: 1350000, variance: "2 Phím", description: "Điều Khiển Từ Xa Tương Thích Homekit" },
  { id: 150, name: "Giàn Phơi Đồ Thông Minh Aqara H1 Zigbee", price: 12899000, variance: "", description: "Chịu Lực Lớn- Tích Hợp Đèn Sấy Khô Khử Trùng Điều Khiển Từ Xa Tạo Ngữ Cảnh" },
  { id: 151, name: "Quạt Để Bàn Mini Xiaomi F5", price: 499000, variance: "", description: "Fan White" },
  { id: 152, name: "Cảm Biến Hiện Diện Người Zigbee Tuya", price: 1319000, variance: "", description: "Độ Chính Xác Cao Điều Chỉnh Độ Nhạy (Hỗ trợ HomeAssistant)" },
  { id: 153, name: "Bộ Điều Khiển Độ Sáng Thông Minh Dimmer Aqara T1 Pro", price: 1699000, variance: "", description: "Điều Chỉnh Nhiệt Độ Màu Kép Điều Khiển Từ Xa" },
  { id: 154, name: "Đèn LED Dây Thông Minh Aqara COB T1 5M Siêu Sáng Siêu Mịn", price: 1200000, variance: "COB T1 8w 576 bóng/m", description: "Điều Khiển Trên Điện Thoại Trang trí Cầu Thang Nhà Cửa" },
  { id: 155, name: "Đèn LED Dây Thông Minh Aqara COB T1 5M Siêu Sáng Siêu Mịn", price: 1100000, variance: "T1 SMD 7w 120 bóng/m", description: "Điều Khiển Trên Điện Thoại Trang trí Cầu Thang Nhà Cửa" },
  { id: 156, name: "Công Tắc Cửa Cuốn Thông Minh WiFi + BLE Hunonic Door", price: 1809000, variance: "Đen", description: "App Tiếng Việt Điều Khiển Từ Xa Qua Điện Thoại BH 24 Tháng" },
  { id: 157, name: "Công Tắc Cửa Cuốn Thông Minh WiFi + BLE Hunonic Door", price: 1809000, variance: "Trắng", description: "App Tiếng Việt Điều Khiển Từ Xa Qua Điện Thoại BH 24 Tháng" },
  { id: 158, name: "Đèn Led Dây Trang Trí RGB Aqara Strip T1 2m Zigbee", price: 1390000, variance: "", description: "16 Triệu Màu Hẹn Giờ Điều Khiển Từ Xa Tích Hợp Micro Đồng Bộ Nhạc" },
  { id: 159, name: "Loa Thông Minh OLLI MAIKA WiFi Bluetooth", price: 3345000, variance: "", description: "Trợ Lý Ảo Tiếng Việt Điều Khiển Nhà Thông Minh Thuần Việt" },
  { id: 160, name: "Đèn Yeelight W3 Smart LED Bulb Color 8W E26/E27", price: 399000, variance: "", description: "Điều Khiển Qua Điện Thoại Tích Hợp Chroma Razer" },
  { id: 161, name: "Đồng hồ LED 3D Thông Minh Để Bàn Làm Việc Treo Tường", price: 175000, variance: "Đèn Trắng", description: "Đa Chức Năng Báo Thức Nhiệt Độ Cảm Biến Âm Thanh" },
  { id: 162, name: "Đồng hồ LED 3D Thông Minh Để Bàn Làm Việc Treo Tường", price: 195000, variance: "Đèn Xanh+Củ Sạc", description: "Đa Chức Năng Báo Thức Nhiệt Độ Cảm Biến Âm Thanh" },
  { id: 163, name: "Đồng hồ LED 3D Thông Minh Để Bàn Làm Việc Treo Tường", price: 175000, variance: "Đèn Xanh", description: "Đa Chức Năng Báo Thức Nhiệt Độ Cảm Biến Âm Thanh" },
  { id: 164, name: "Đồng hồ LED 3D Thông Minh Để Bàn Làm Việc Treo Tường", price: 195000, variance: "Đèn Trắng+Củ Sạc", description: "Đa Chức Năng Báo Thức Nhiệt Độ Cảm Biến Âm Thanh" },
  { id: 165, name: "Công Tắc Cửa Cuốn Thông Minh WiFi Hunonic Datic", price: 615000, variance: "Trắng+ Đế Nổi", description: "App Tiếng Việt Điều Khiển Từ Xa Qua Điện Thoại- DATIC-SDOOR" },
  { id: 166, name: "Công Tắc Cửa Cuốn Thông Minh WiFi Hunonic Datic", price: 609000, variance: "Đen", description: "App Tiếng Việt Điều Khiển Từ Xa Qua Điện Thoại- DATIC-SDOOR" },
  { id: 167, name: "Công Tắc Cửa Cuốn Thông Minh WiFi Hunonic Datic", price: 615000, variance: "Đen + Đế Nổi", description: "App Tiếng Việt Điều Khiển Từ Xa Qua Điện Thoại- DATIC-SDOOR" },
  { id: 168, name: "Công Tắc Cửa Cuốn Thông Minh WiFi Hunonic Datic", price: 609000, variance: "Trắng", description: "App Tiếng Việt Điều Khiển Từ Xa Qua Điện Thoại- DATIC-SDOOR" },
  { id: 169, name: "Công Tắc Cửa Cuốn Thông Minh WiFi Hunonic Datic", price: 615000, variance: "Đen + Đế Âm", description: "App Tiếng Việt Điều Khiển Từ Xa Qua Điện Thoại- DATIC-SDOOR" },
  { id: 170, name: "Công Tắc Cửa Cuốn Thông Minh WiFi Hunonic Datic", price: 615000, variance: "Trắng+ Đế Âm", description: "App Tiếng Việt Điều Khiển Từ Xa Qua Điện Thoại- DATIC-SDOOR" },
  { id: 171, name: "Bộ Tô Vít Đa Năng 115 Chi Tiết", price: 99000, variance: "Bộ 24 Đầu", description: "Sửa Chữa Điện Thoại Laptop Vật Dụng Gia Đình Chuyên Nghiệp Cao Cấp" },
  { id: 172, name: "Bộ Tô Vít Đa Năng 115 Chi Tiết", price: 139000, variance: "Bộ 115 Chi Tiết", description: "Sửa Chữa Điện Thoại Laptop Vật Dụng Gia Đình Chuyên Nghiệp Cao Cấp" },
  { id: 173, name: "Đèn Led Dây RGB Aqara Mở Rộng Light Strip T1 Matter Nối dài 1 mét", price: 390000, variance: "", description: "16 Triệu Màu Hẹn Giờ Điều Khiển Từ Xa Đồng Bộ Nhạc" },
  { id: 174, name: "Cảm Biến Chuyển Động Thông Minh Aqara P1 MS-S02 Bản Quốc Tế", price: 689000, variance: "", description: "Pin 5 Năm Chỉnh Độ Nhạy Góc Quét 170 Độ Zigbee 3.0" },
  { id: 175, name: "Cảm Biến Cửa Thông Minh Aqara P2 Door and Window Sensor P2", price: 860000, variance: "", description: "Pin 5 Năm Tương Thích Matter & Thread Bản Quốc Tế" },
  { id: 176, name: "Máy Sưởi Phòng Tắm Thông Minh Aqara T1 Zigbee 2800W", price: 5990000, variance: "", description: "Tích Hợp Đèn Trần Quạt Sưởi - Điều Khiển Từ Xa Tương Thích HomeKit" },
  { id: 177, name: "Đèn Bàn Đèn Sạc Tích Điện Trang Trí RGB Yeelight Atmosphere Lamp White", price: 950000, variance: "Trắng", description: "Bảo Vệ Mắt Tiết Kiệm Điện Tích Hợp Đa Năng" },
  { id: 178, name: "Đèn Bàn Đèn Sạc Tích Điện Trang Trí RGB Yeelight Atmosphere Lamp White", price: 950000, variance: "Đen", description: "Bảo Vệ Mắt Tiết Kiệm Điện Tích Hợp Đa Năng" },
  { id: 179, name: "Thiết Bị Mở Rộng Sóng Tuya Zigbee Repeater", price: 515000, variance: "", description: "Kích Sóng Zigbee Hỗ Trợ Smart Life Chuẩn USB Nguồn 5V" },
  { id: 180, name: "Cảm Biến Nhiệt Độ Độ Ẩm Áp Suất Aqara T1", price: 550000, variance: "", description: "Zigbee 3.0 - Độ Chính Xác Cao Hỗ Trợ Bảo Vệ Sức Khoẻ Chính Hãng (NEW)" },
  { id: 181, name: "Quạt Sạc Quạt Tích Điện Để Bàn Đa Năng COMET 7W CRF1506", price: 569000, variance: "", description: "Pin 1500mAh 4 Cấp Độ Gió Nhỏ Gọn Nhựa ABS Cao Cấp" },
  { id: 182, name: "Thanh Đèn LED 3D RGB Nháy Theo Nhạc", price: 256000, variance: "USB + Sạc", description: "16 Triệu Màu Cảm Ứng Âm Thanh Trang Trí Nhà Cửa" },
  { id: 183, name: "Thanh Đèn LED 3D RGB Nháy Theo Nhạc", price: 236700, variance: "Kèm USB", description: "16 Triệu Màu Cảm Ứng Âm Thanh Trang Trí Nhà Cửa" },
  { id: 184, name: "Công Tắc WiFi Thông Minh Cảm Ứng Hunonic Datic 2 Nút 1 Ổ", price: 569000, variance: "Đen", description: "App Tiếng Việt Điều Khiển Qua App Điện Thoại Hẹn Giờ Bật Tắt" },
  { id: 185, name: "Công Tắc WiFi Thông Minh Cảm Ứng Hunonic Datic 2 Nút 1 Ổ", price: 569000, variance: "Trắng", description: "App Tiếng Việt Điều Khiển Qua App Điện Thoại Hẹn Giờ Bật Tắt" },
  { id: 186, name: "Công Tắc Cảm Ứng Thông Minh Wifi Hunonic Datic 1-2-3-4 Nút", price: 479000, variance: "2 Nút - Trắng", description: "App Tiếng Việt Điều Khiển Từ Xa Điều Khiển Giọng Nói" },
  { id: 187, name: "Công Tắc Cảm Ứng Thông Minh Wifi Hunonic Datic 1-2-3-4 Nút", price: 465000, variance: "1 Nút - Trắng", description: "App Tiếng Việt Điều Khiển Từ Xa Điều Khiển Giọng Nói" },
  { id: 188, name: "Công Tắc Cảm Ứng Thông Minh Wifi Hunonic Datic 1-2-3-4 Nút", price: 549000, variance: "4 Nút - Đen", description: "App Tiếng Việt Điều Khiển Từ Xa Điều Khiển Giọng Nói" },
  { id: 189, name: "Công Tắc Cảm Ứng Thông Minh Wifi Hunonic Datic 1-2-3-4 Nút", price: 497000, variance: "3 Nút - Đen", description: "App Tiếng Việt Điều Khiển Từ Xa Điều Khiển Giọng Nói" },
  { id: 190, name: "Công Tắc Cảm Ứng Thông Minh Wifi Hunonic Datic 1-2-3-4 Nút", price: 479000, variance: "2 Nút - Đen", description: "App Tiếng Việt Điều Khiển Từ Xa Điều Khiển Giọng Nói" },
  { id: 191, name: "Công Tắc Cảm Ứng Thông Minh Wifi Hunonic Datic 1-2-3-4 Nút", price: 465000, variance: "1 Nút - Đen", description: "App Tiếng Việt Điều Khiển Từ Xa Điều Khiển Giọng Nói" },
  { id: 192, name: "Công Tắc Cảm Ứng Thông Minh Wifi Hunonic Datic 1-2-3-4 Nút", price: 479000, variance: "3 Nút - Trắng", description: "App Tiếng Việt Điều Khiển Từ Xa Điều Khiển Giọng Nói" },
  { id: 193, name: "Công Tắc Cảm Ứng Thông Minh Wifi Hunonic Datic 1-2-3-4 Nút", price: 549000, variance: "4 Nút - Trắng", description: "App Tiếng Việt Điều Khiển Từ Xa Điều Khiển Giọng Nói" },
  { id: 194, name: "Ổ Cắm Chuyển Đổi Đầu 3 Châú Sang 2 Châú", price: 40000, variance: "", description: "220V" },
  { id: 195, name: "Động Cơ Rèm Cửa Cuốn Thông Minh Aqara Smart Roller Shade Cotroller Zigbee", price: 3779000, variance: "", description: "Hẹn Giờ Điều Khiển Từ Xa Tương Thích HomeKit" },
  { id: 196, name: "Quạt Sạc Mini Cầm Tay Gấp Gọn Comet CRF0904 3W", price: 269000, variance: "", description: "Sạc USB Tiện Lợi Nhỏ Gọn Dung Lượng Pin 1.200mAh" },
  { id: 197, name: "Dây Đèn LED Tình Yêu", price: 349000, variance: "Lucki+Fairy-10M-2SẠC", description: "Phù hợp Tỏ Tình Cầu Hôn Hấp Hôn 16 Triệu Màu Nháy Theo Nhạc Kết Nối App & Remote" },
  { id: 198, name: "Dây Đèn LED Tình Yêu", price: 232700, variance: "LuckiLight-10M", description: "Phù hợp Tỏ Tình Cầu Hôn Hấp Hôn 16 Triệu Màu Nháy Theo Nhạc Kết Nối App & Remote" },
  { id: 199, name: "Dây Đèn LED Tình Yêu", price: 356000, variance: "LuckiLight-15M-SẠC", description: "Phù hợp Tỏ Tình Cầu Hôn Hấp Hôn 16 Triệu Màu Nháy Theo Nhạc Kết Nối App & Remote" },
  { id: 200, name: "Dây Đèn LED Tình Yêu", price: 469400, variance: "2 Lucki 10M - 2SẠC", description: "Phù hợp Tỏ Tình Cầu Hôn Hấp Hôn 16 Triệu Màu Nháy Theo Nhạc Kết Nối App & Remote" },
  { id: 201, name: "Dây Đèn LED Tình Yêu", price: 252700, variance: "LuckiLight-10M-SẠC", description: "Phù hợp Tỏ Tình Cầu Hôn Hấp Hôn 16 Triệu Màu Nháy Theo Nhạc Kết Nối App & Remote" },
  { id: 202, name: "Dây Đèn LED Tình Yêu", price: 336000, variance: "LuckiLight-15M", description: "Phù hợp Tỏ Tình Cầu Hôn Hấp Hôn 16 Triệu Màu Nháy Theo Nhạc Kết Nối App & Remote" },
  { id: 203, name: "Camera Thông Minh Aqara E1 WiFi", price: 1749000, variance: "", description: "Chuẩn Nét 2K Xoay 360º Phát Hiện Người Hỗ Trợ HomeKit Google Home" },
  { id: 204, name: "Công Tắc Cảm Ứng WiFi Hunonic 2 Nút 1 Ổ Hình Chữ Nhật Viền Vàng", price: 979000, variance: "Đen", description: "Hẹn Giờ Bật Tắt Điều Khiển Từ Xa Tiện Lợi Sang Trọng" },
  { id: 205, name: "Công Tắc Cảm Ứng WiFi Hunonic 2 Nút 1 Ổ Hình Chữ Nhật Viền Vàng", price: 979000, variance: "Trắng", description: "Hẹn Giờ Bật Tắt Điều Khiển Từ Xa Tiện Lợi Sang Trọng" },
  { id: 206, name: "Quạt Sạc Quạt Cầm Tay COMET CRF1104 3W", price: 179000, variance: "", description: "Pin 1200mAh Nhựa ABS Cao Cấp An Toàn Mát Mẻ" },
  { id: 207, name: "Máy Lọc Không Khí Levoit Core Mini", price: 2899000, variance: "", description: "Diệt Khuẩn Công nghệ QuietKEAP Chính Hãng" },
  { id: 208, name: "Module Thông Minh Aqara T1 Zigbee Công Tắc 1 Kênh", price: 749000, variance: "KHÔNG Dây Nguội/ N", description: "Hẹn Giờ Điều Khiển Thiết Bị Tương Thích HomeKit Bản Quốc Tế" },
  { id: 209, name: "Module Thông Minh Aqara T1 Zigbee Công Tắc 1 Kênh", price: 649000, variance: "CÓ Dây Nguội/ N", description: "Hẹn Giờ Điều Khiển Thiết Bị Tương Thích HomeKit Bản Quốc Tế" },
  { id: 210, name: "Công Tắc Không Dây Dán Tường Aqara H1 Zigbee 2 Nút", price: 890000, variance: "", description: "Pin 5 Năm Phản Hồi Nhanh Tạo Ngữ Cảnh Thông Minh Bản Quốc Tế" },
  { id: 211, name: "Công Tắc Không Dây Núm Xoay Aqara Dimmer H1 Zigbee", price: 989000, variance: "", description: "Công Tắc Ngữ Cảnh Điều Chỉnh Đèn Rèm Cửa Đo Điện Năng Quốc Tế" },
  { id: 212, name: "Đèn Led Thông Minh Yeelight Lightstrip 1S", price: 850000, variance: "", description: "16 Triệu Màu - Điều Chỉnh Màu Điều Khiển Từ Xa Tích Hợp Mirco Nháy Theo Nhạc" },
  { id: 213, name: "Đèn Ngủ Cảm Biến Ánh Sáng Cắm Điện Yeelight 0.5W Nhỏ Gọn", price: 180000, variance: "", description: "Tự Động Bật Khi Trời Tối Không Chói Mắt Bản EU 2 Chấu" },
  { id: 214, name: "Cảm Biến Nhiệt Độ và Độ Ẩm Hunonic WiFi/Bluetooth", price: 279000, variance: "", description: "App Tiếng Việt Kiểm Soát Môi Trường Tích Hợp Ngữ Cảnh Thông Minh" },
  { id: 215, name: "Cảm Biến Hiện Diện Lumi", price: 1589000, variance: "", description: "Tích Hợp Công Nghệ PIR và Radar - Phát Hiện Nhịp Thở Mở Đèn Thông Minh - Hàng Chính Hãng" },
  { id: 216, name: "Cảm Biến Cửa Thông Minh Aqara Door Sensor T1 Zigbee 3.0", price: 500000, variance: "", description: "Chống Trộm Nhận Thông Báo Về Điện Thoại Pin 2 Năm" },
  { id: 217, name: "Bóng Đèn LED Thông Minh Xiaomi Aqara T1 8.5W Zigbee", price: 490000, variance: "", description: "Điều Chỉnh Màu 2700K-6500K Điều Khiển Từ Xa Tương Thích HomeKit" },
  { id: 218, name: "Đèn Âm Trần Downlight Yeelight M2/ M2 Pro", price: 465000, variance: "Downlight M2", description: "Hẹn Giờ Bật Tắt Từ Xa Điều Chỉnh Màu Sắc Độ Sáng Tương Thích Homekit" },
  { id: 219, name: "Đèn Âm Trần Downlight Yeelight M2/ M2 Pro", price: 570000, variance: "Downlight M2 Pro", description: "Hẹn Giờ Bật Tắt Từ Xa Điều Chỉnh Màu Sắc Độ Sáng Tương Thích Homekit" },
  { id: 220, name: "Đèn Âm Trần Downlight Yeelight M2/ M2 Pro", price: 535000, variance: "Spotlight M2", description: "Hẹn Giờ Bật Tắt Từ Xa Điều Chỉnh Màu Sắc Độ Sáng Tương Thích Homekit" },
  { id: 221, name: "Bộ Điều Khiển Rèm Cuốn Thông Minh Aqara Roller Shade Driver E1", price: 2400000, variance: "", description: "Tự Động Điều Khiển Từ Xa Giọng Nói Tương Thích HomeKit" },
  { id: 222, name: "CB Aptomat Cầu Dao WiFi Thông Minh Hunonic Notec 63A", price: 1189000, variance: "63A", description: "App Tiếng Việt Điều khiển Qua Điện ThoạI Đo Điện BH 24 Tháng" },
  { id: 223, name: "CB Aptomat Cầu Dao WiFi Thông Minh Hunonic Notec 63A", price: 1189000, variance: "40A", description: "App Tiếng Việt Điều khiển Qua Điện ThoạI Đo Điện BH 24 Tháng" },
  { id: 224, name: "CB Aptomat Cầu Dao WiFi Thông Minh Hunonic Notec 63A", price: 1189000, variance: "80A", description: "App Tiếng Việt Điều khiển Qua Điện ThoạI Đo Điện BH 24 Tháng" },
  { id: 225, name: "Camera Hub Thông Minh Aqara G2H Pro 1080p Wifi/Zigbee 3.0", price: 2589000, variance: "", description: "Nhận Dạng Khuôn Mặt Tích Hợp Đèn Hồng Ngoại,Phát Hiện Người" },
  { id: 226, name: "Ổ Cắm Điện Thông Minh Đôi Zigbee Viền Vàng Tuya Âm Tường Chữ Nhật 10A", price: 780000, variance: "Trắng,Zigbee", description: "Điều Khiển Từ Xa Hẹn Giờ" },
  { id: 227, name: "Ổ Cắm Điện Thông Minh Đôi Zigbee Viền Vàng Tuya Âm Tường Chữ Nhật 10A", price: 780000, variance: "Đen,Zigbee", description: "Điều Khiển Từ Xa Hẹn Giờ" },
  { id: 228, name: "Chuông Báo Động Báo Khách Thông Minh Zigbee Tuya", price: 582400, variance: "Zigbee", description: "Cảm Biến Nhiệt Độ và Độ Ẩm" },
  { id: 229, name: "Chuông Báo Động Báo Khách Thông Minh Zigbee Tuya", price: 637000, variance: "Wifi", description: "Cảm Biến Nhiệt Độ và Độ Ẩm" },
  { id: 230, name: "Ổ Cắm Điện Wifi Thông Minh Hunonic SK01", price: 219000, variance: "", description: "App Tiếng Việt Điều Khiển Từ Xa Trên Điện Thoại Hẹn Giờ Điều Khiển Giọng Nói" },
  { id: 231, name: "Bóng Đèn Thông Minh Dây Tóc Dáng Dài Dây Tóc Sợi Đốt Yeelight Filament ST64 WiFi", price: 265000, variance: "", description: "Hẹn Giờ Bật Tắt Từ Xa" },
  { id: 232, name: "Găng Tay Bảo Hộ Phủ Sơn Màu Xanh N518", price: 50000, variance: "Combo 3 đôi", description: "Chống Dầu Găng Tay Vải Phủ Sơn Bám Dính Tốt Chống Cắt" },
  { id: 233, name: "Găng Tay Bảo Hộ Phủ Sơn Màu Xanh N518", price: 18000, variance: "Lẻ 1 đôi", description: "Chống Dầu Găng Tay Vải Phủ Sơn Bám Dính Tốt Chống Cắt" },
  { id: 234, name: "Công Tắc Thông Minh 16A Điều Khiển Từ Xa Qua Điện Thoại", price: 139000, variance: "CT Datic Basic", description: "bằng WIFI 3G 4G Hẹn Giờ Bật Tắt App Tuya Smart Life Google" },
  { id: 235, name: "Công Tắc Thông Minh 16A Điều Khiển Từ Xa Qua Điện Thoại", price: 159000, variance: "CT Mini 16A", description: "bằng WIFI 3G 4G Hẹn Giờ Bật Tắt App Tuya Smart Life Google" },
  { id: 236, name: "Công Tắc Thông Minh 16A Điều Khiển Từ Xa Qua Điện Thoại", price: 322000, variance: "CT Mini Hunonic", description: "bằng WIFI 3G 4G Hẹn Giờ Bật Tắt App Tuya Smart Life Google" },
  { id: 237, name: "Đồng Hồ LED Đa Chức Năng", price: 166600, variance: "Đen,Kèm USB", description: "Hiển Thị Nhiệt Độ Báo Thức Ánh Sáng Tự Động - Smart Clock" },
  { id: 238, name: "Đồng Hồ LED Đa Chức Năng", price: 186000, variance: "Trắng,USB + Sạc", description: "Hiển Thị Nhiệt Độ Báo Thức Ánh Sáng Tự Động - Smart Clock" },
  { id: 239, name: "Đồng Hồ LED Đa Chức Năng", price: 166000, variance: "Trắng,Kèm USB", description: "Hiển Thị Nhiệt Độ Báo Thức Ánh Sáng Tự Động - Smart Clock" },
  { id: 240, name: "Đồng Hồ LED Đa Chức Năng", price: 186000, variance: "Đen,USB + Sạc", description: "Hiển Thị Nhiệt Độ Báo Thức Ánh Sáng Tự Động - Smart Clock" },
  { id: 241, name: "Đèn Muỗi Kiêm Vợt Muỗi Yeelight Mosquito Repellant Lamp", price: 630000, variance: "", description: "Tự Động Bật Tắt Thân Thiện Môi Trường Diệt Muỗi An Toàn" },
  { id: 242, name: "Đèn Phi Hành Gia Galaxy Chiếu Sao", price: 455500, variance: "Dây USB Kèm", description: "Thiên Hà Trang Trí Decor Bàn Làm Việc Nhà Cửa Phòng Ngủ" },
  { id: 243, name: "Đèn Phi Hành Gia Galaxy Chiếu Sao", price: 475000, variance: "Dây USB + Sạc", description: "Thiên Hà Trang Trí Decor Bàn Làm Việc Nhà Cửa Phòng Ngủ" },
  { id: 244, name: "Cảm Biến Chuyển Động Tuya Zigbee 3.0 Tròn Gắn Trần", price: 379000, variance: "Zigbee 3.0 Gắn Trần", description: "Điều Khiển Từ Xa Cảnh Báo Di Chuyển Tự Động Bật Đèn" },
  { id: 245, name: "Cảm Biến Chuyển Động Tuya Zigbee 3.0 Tròn Gắn Trần", price: 412600, variance: "Zigbee Chống báo giả", description: "Điều Khiển Từ Xa Cảnh Báo Di Chuyển Tự Động Bật Đèn" },
  { id: 246, name: "Bộ Điều Khiển Hồng Ngoại Tuya Zigbee", price: 639000, variance: "", description: "Điều Khiển Tivi Máy Lạnh Quạt - Kết Nối qua Hub Zigbee" },
  { id: 247, name: "Camera Aqara G3 2K AI Tracking", price: 3789000, variance: "", description: "Xoay 360° Tích Hợp Hub Zigbee & Hồng Ngoại Bảo Vệ Nhà Cửa Thông Minh" },
  { id: 248, name: "Bút Thử Điện Đa Năng 110-220V", price: 15000, variance: "", description: "Bút Kiểm Tra Điện Đầu Dẹp Kiêm Tua Vít" },
  { id: 249, name: "Nút Bấm Ngữ Cảnh Thông Minh Aqara Mini Switch T1", price: 500000, variance: "", description: "Zigbee 3.0 - Pin 2 Năm Tương Thích HomeKit Bản Quốc Tế" },
  { id: 250, name: "Động Cơ Rèm Kéo Ngang Thông Minh Aqara Zigbee 3.0", price: 2899000, variance: "", description: "Chịu Lực 50kg - Điều Khiển Từ Xa Hoạt Động Êm Ái Tương thích HomeKit" },
  { id: 251, name: "Khóa Cửa Thông Minh Aqara N100 Smart Door Lock Zigbee 3.0", price: 6990000, variance: "", description: "Cảm Biến Vân Tay Tích Hợp Chuông Điều Khiển Giọng Nói" },
  { id: 252, name: "Quạt Sạc Tích Điện Mini Kẹp Bàn Comet CRF0705 5W", price: 359000, variance: "", description: "Xoay 360 Độ Kẹp Xe Kẹp Ghế Để Bàn" },
  { id: 253, name: "Cảm Biến Hiện Diện Aqara Presence FP2", price: 2749700, variance: "", description: "Nhận Diện Người Té Ngã Nhận Diện Theo Vùng Kết Nối Wi-Fi Tương Thích HomeKit" },
  { id: 254, name: "Cảm Biến Tràn Nước Thông Minh Aqara Water Leak Sensor", price: 449000, variance: "", description: "Phát Hiện Ngập Nước Bảo Vệ An Toàn Cho Ngôi Nhà Bản Quốc Tế" },
  { id: 255, name: "Công tắc thông minh Aqara Dual Relay Module T2 Matter DCM-K01", price: 1059700, variance: "", description: "Zigbee Bản Quốc Tế - Tương Thích HomeKit và Alexa" },
  { id: 256, name: "Công Tắc Thông Minh Aqara Q1 Zigbee Chữ Nhật 1 Nút 2 Nút", price: 1289000, variance: "2 NÚT,KhÔNG CÓ Dây Nguội", description: "Điều Khiển Từ Xa Hẹn Giờ Tương Thích HomeKit Bản Quốc Tế" },
  { id: 257, name: "Công Tắc Thông Minh Aqara Q1 Zigbee Chữ Nhật 1 Nút 2 Nút", price: 1189000, variance: "1 NÚT,CÓ Dây Nguội", description: "Điều Khiển Từ Xa Hẹn Giờ Tương Thích HomeKit Bản Quốc Tế" },
  { id: 258, name: "Công Tắc Thông Minh Aqara Q1 Zigbee Chữ Nhật 1 Nút 2 Nút", price: 1289000, variance: "2 NÚT,CÓ Dây Nguội", description: "Điều Khiển Từ Xa Hẹn Giờ Tương Thích HomeKit Bản Quốc Tế" },
  { id: 259, name: "Công Tắc Thông Minh Aqara Q1 Zigbee Chữ Nhật 1 Nút 2 Nút", price: 1189000, variance: "1 NÚT,KhÔNG CÓ Dây Nguội", description: "Điều Khiển Từ Xa Hẹn Giờ Tương Thích HomeKit Bản Quốc Tế" },
  { id: 260, name: "Đèn LED Dây Thông Minh Aqara COB H1 5M Siêu Sáng Mịn", price: 2490000, variance: "COB H1 8w 840 bóng/m", description: "Điều Khiển Từ Xa Trên Điện Thoại Trang Trí Cầu Thang Nhà Cửa" },
  { id: 261, name: "Đèn LED Dây Thông Minh Aqara COB H1 5M Siêu Sáng Mịn", price: 1899000, variance: "SMD H1 10w168 bóng/m", description: "Điều Khiển Từ Xa Trên Điện Thoại Trang Trí Cầu Thang Nhà Cửa" },
  { id: 262, name: "Bộ Điều Khiển Rèm Động Cơ Rèm Kéo Thông Minh Aqara Bot E1", price: 2598000, variance: "Ray vuông", description: "Dùng Pin Hẹn Giờ Tự Động Đóng Mở Tương Thích HomeKit" },
  { id: 263, name: "Bộ Điều Khiển Rèm Động Cơ Rèm Kéo Thông Minh Aqara Bot E1", price: 2899000, variance: "Ray tròn", description: "Dùng Pin Hẹn Giờ Tự Động Đóng Mở Tương Thích HomeKit" },
  { id: 264, name: "Chuông Cửa Thông Minh Aqara G4 Video Doorbell WiFi", price: 2990000, variance: "", description: "Tích Hợp AI Chuông Nhận Diện Khuôn Mặt HD 1080p Trò Chuyện 2 Chiều" },
  { id: 265, name: "Ổ Cắm Âm Tường Chữ Nhật Wifi Tuya", price: 791700, variance: "Đen", description: "Điều Khiển Từ Xa Đo Công Suất Tiêu Thụ Điện Điều Khiển Giọng Nói" },
  { id: 266, name: "Ổ Cắm Âm Tường Chữ Nhật Wifi Tuya", price: 791700, variance: "Trắng", description: "Điều Khiển Từ Xa Đo Công Suất Tiêu Thụ Điện Điều Khiển Giọng Nói" },
  { id: 267, name: "Cảm Biến Báo Cháy Báo Khói Zigbee Tuya Smart", price: 839000, variance: "CB Khí Gas Zigbee", description: "Báo Động Cảnh Báo Trên Điện Thoại Bảo Vệ An Toàn Gia Đình" },
  { id: 268, name: "Cảm Biến Báo Cháy Báo Khói Zigbee Tuya Smart", price: 700700, variance: "CB Khói Zigbee", description: "Báo Động Cảnh Báo Trên Điện Thoại Bảo Vệ An Toàn Gia Đình" },
  { id: 269, name: "Cảm Biến Rung Tuya Zigbee Thông Minh", price: 489000, variance: "", description: "Tương Thích Alexa" },
  { id: 270, name: "Đèn Led Thông Minh Thanh Dán Tủ Cảm Biến Pin Sạc Yeelight 20CM 2700K/4000K", price: 489000, variance: "L40-4000K-BLACK", description: "Tích Hợp Cảm Biến Chuyển Động Ánh Sáng" },
  { id: 271, name: "Đèn Led Thông Minh Thanh Dán Tủ Cảm Biến Pin Sạc Yeelight 20CM 2700K/4000K", price: 630000, variance: "L60-4000K-BLACK", description: "Tích Hợp Cảm Biến Chuyển Động Ánh Sáng" },
  { id: 272, name: "Đèn Led Thông Minh Thanh Dán Tủ Cảm Biến Pin Sạc Yeelight 20CM 2700K/4000K", price: 630000, variance: "L60-2700K-BLACK", description: "Tích Hợp Cảm Biến Chuyển Động Ánh Sáng" },
  { id: 273, name: "Đèn Led Thông Minh Thanh Dán Tủ Cảm Biến Pin Sạc Yeelight 20CM 2700K/4000K", price: 365000, variance: "L20-4000K-BLACK", description: "Tích Hợp Cảm Biến Chuyển Động Ánh Sáng" },
  { id: 274, name: "Đèn Led Thông Minh Thanh Dán Tủ Cảm Biến Pin Sạc Yeelight 20CM 2700K/4000K", price: 365000, variance: "L20-2700K-SILVER", description: "Tích Hợp Cảm Biến Chuyển Động Ánh Sáng" },
  { id: 275, name: "Đèn Led Thông Minh Thanh Dán Tủ Cảm Biến Pin Sạc Yeelight 20CM 2700K/4000K", price: 489000, variance: "L40-2700K-SILVER", description: "Tích Hợp Cảm Biến Chuyển Động Ánh Sáng" },
  { id: 276, name: "Công Tắc Thông Minh Wifi Tuya Hình Chữ Nhật Cảm Ứng 2-3-4 Nút", price: 339000, variance: "2 Gang,CÓ dây nguội", description: "Điều Khiển Trên Điện Thoại App Smart Life" },
  { id: 277, name: "Công Tắc Thông Minh Wifi Tuya Hình Chữ Nhật Cảm Ứng 2-3-4 Nút", price: 399000, variance: "4 Gang,CÓ dây nguội", description: "Điều Khiển Trên Điện Thoại App Smart Life" },
  { id: 278, name: "Công Tắc Thông Minh Wifi Tuya Hình Chữ Nhật Cảm Ứng 2-3-4 Nút", price: 354000, variance: "3 Gang,CÓ dây nguội", description: "Điều Khiển Trên Điện Thoại App Smart Life" },
  { id: 279, name: "Dây Đèn Led LuckiLight Mini FairyLight Thông Minh", price: 279000, variance: "15M + CỦ SẠC", description: "Trang Trí Lễ Tết Nhà Cửa Nháy Theo Nhạc Điều Khiển Qua App" },
  { id: 280, name: "Dây Đèn Led LuckiLight Mini FairyLight Thông Minh", price: 250000, variance: "10M + CỦ SẠC", description: "Trang Trí Lễ Tết Nhà Cửa Nháy Theo Nhạc Điều Khiển Qua App" },
  { id: 281, name: "Dây Đèn Led LuckiLight Mini FairyLight Thông Minh", price: 259700, variance: "15M", description: "Trang Trí Lễ Tết Nhà Cửa Nháy Theo Nhạc Điều Khiển Qua App" },
  { id: 282, name: "Dây Đèn Led LuckiLight Mini FairyLight Thông Minh", price: 230000, variance: "10M", description: "Trang Trí Lễ Tết Nhà Cửa Nháy Theo Nhạc Điều Khiển Qua App" },
  { id: 283, name: "Công Tắc Âm Tường Thông Minh 1-2-3 Nút Aqara H1 Vuông", price: 749000, variance: "1 Nút,CÓ Dây Nguội", description: "Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Điều Khiển Giọng Nói" },
  { id: 284, name: "Công Tắc Âm Tường Thông Minh 1-2-3 Nút Aqara H1 Vuông", price: 1490000, variance: "3 Nút,CÓ Dây Nguội", description: "Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Điều Khiển Giọng Nói" },
  { id: 285, name: "Công Tắc Âm Tường Thông Minh 1-2-3 Nút Aqara H1 Vuông", price: 1590000, variance: "3 Nút,KHÔNG Dây Nguội", description: "Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Điều Khiển Giọng Nói" },
  { id: 286, name: "Công Tắc Âm Tường Thông Minh 1-2-3 Nút Aqara H1 Vuông", price: 849000, variance: "2 Nút,CÓ Dây Nguội", description: "Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Điều Khiển Giọng Nói" },
  { id: 287, name: "Công Tắc Âm Tường Thông Minh 1-2-3 Nút Aqara H1 Vuông", price: 799000, variance: "1 Nút,KHÔNG Dây Nguội", description: "Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Điều Khiển Giọng Nói" },
  { id: 288, name: "Công Tắc Âm Tường Thông Minh 1-2-3 Nút Aqara H1 Vuông", price: 899000, variance: "2 Nút,KHÔNG Dây Nguội", description: "Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Điều Khiển Giọng Nói" },
  { id: 289, name: "Đèn Cảm Biến Ngăn Kéo Tích Điện Yeelight Drawer A6", price: 770000, variance: "", description: "Tích Hợp Cảm Biến Thông Minh Dung Lượng Pin Lớn Set 4 Chiếc" },
  { id: 290, name: "Công Tắc Cảm ứng Hunonic Datic", price: 720000, variance: "Trắng", description: "Công Suất Lớn WiFi Chống Giật Bình Nóng Lạnh Điều Hoà - Điều Khiển Từ Xa App Tiếng Việt" },
  { id: 291, name: "Công Tắc Cảm ứng Hunonic Datic", price: 720000, variance: "Đen", description: "Công Suất Lớn WiFi Chống Giật Bình Nóng Lạnh Điều Hoà - Điều Khiển Từ Xa App Tiếng Việt" },
  { id: 292, name: "Bộ 2 Tua Vít Cao Cấp TOTAL", price: 69000, variance: "", description: "" },
  { id: 293, name: "Cảm Biến Cửa Thông Minh Aqara Door Sensor MCCGQ11LM", price: 390000, variance: "", description: "Bảo Vệ Nhà Cửa Bản Quốc Tế Bảo Hành 12 Tháng" },
  { id: 294, name: "Cảm Biến Khói Aqara Smoke Sensor Zigbee 3.0", price: 1690000, variance: "Cảm Biến Khí Gas", description: "Báo Cháy Thông Minh Bảo Vệ Nhà Cửa Pin 10 Năm Tương Thích Homekit" },
  { id: 295, name: "Cảm Biến Khói Aqara Smoke Sensor Zigbee 3.0", price: 1390000, variance: "Cảm Biến Khói", description: "Báo Cháy Thông Minh Bảo Vệ Nhà Cửa Pin 10 Năm Tương Thích Homekit" },
  { id: 296, name: "Cảm Biến Tràn Nước Aqara Water Leak Sensor T1 Zigbee 3.0", price: 520000, variance: "", description: "Phát Hiện Rò Rỉ Báo Động Qua Điện Thoại Bảo Vệ Nhà Cửa" },
  { id: 297, name: "(Quà tặng kèm) Bộ Lì Xì Gieo Quẻ 12 Con Giáp", price: 10000, variance: "", description: "Bao Lì Xì Tết Giáp Thìn 2024" },
  { id: 298, name: "Công Tắc Thông Minh Không Dây Aqara Wireless Mini Switch", price: 349000, variance: "", description: "Tạo Ngữ Cảnh Điều Khiển Thiết Bị Một Nút Pin 2 Năm" },
  { id: 299, name: "Đèn Cắm Trại Đa Năng Yeelight Nhỏ Gọn Đa Năng", price: 630000, variance: "", description: "Điều Chỉnh Độ Sáng Linh Hoạt Tích Hợp Pin Sạc Chống Nước IPX6." },
  { id: 300, name: "Bút Thử Điện 2 Đầu Nanoco NEP1502 Panasonic", price: 19000, variance: "", description: "Nhựa ABS Bền Bỉ An Toàn Tiện Dụng" },
  { id: 301, name: "Camera Ngoài Trời Tapo C310 TP-LINK", price: 1090000, variance: "", description: "Phát Hiện Chuyển Động Gửi Thông Báo Cảnh Báo Âm Thanh Ánh Sáng Chịu Mưa Chịu Nắng" },
  { id: 302, name: "Ổ Cắm Điện Thông Minh WiFi Tuya Công Suất Cao 15A 3750W", price: 499000, variance: "BH 12 Tháng", description: "Hẹn Giờ Điều Khiển Từ Xa Đo Điện Năng Tiêu Thụ Tiết Kiệm Điện" },
  { id: 303, name: "Camera Wifi ICat Outdoor Hunonic", price: 1868000, variance: "KÈM Thẻ Lexar 64G", description: "Chống Thấm Nước Giám Sát Từ Xa Đàm Thoại Hai Chiều Hồng Ngoại Trong Đêm" },
  { id: 304, name: "Camera Wifi ICat Outdoor Hunonic", price: 1814000, variance: "KÈM Thẻ Lexar 32G", description: "Chống Thấm Nước Giám Sát Từ Xa Đàm Thoại Hai Chiều Hồng Ngoại Trong Đêm" },
  { id: 305, name: "Camera Wifi ICat Outdoor Hunonic", price: 1709000, variance: "CHỈ Camera", description: "Chống Thấm Nước Giám Sát Từ Xa Đàm Thoại Hai Chiều Hồng Ngoại Trong Đêm" },
  { id: 306, name: "Camera WiFi Trong Nhà IMOU Ranger 2 3MP", price: 690000, variance: "", description: "Xoay 355 độ Chống Ngược Sáng Phát Hiện Chuyển Động Tích Hợp Còi Báo Đàm Thoại" },
  { id: 307, name: "Camera ngoài trời IMOU Bullet 3 3MP/5MP IPC-S3EP", price: 1590000, variance: "5MP", description: "Hỗ trợ Wi-Fi 6 Phát Hiện Người Chống Nước Tích Hợp Còi Báo Động" },
  { id: 308, name: "Bóng Đèn Led Thông Minh TP-Link Tapo L510E", price: 299000, variance: "", description: "Đèn WiFi Tùy Chỉnh Ánh Sáng Hẹn Giờ Điều Khiển Từ Xa Qua Điện Thoại" },
  { id: 309, name: "Bút Thử Điện Cảm Ứng Thông Minh 2 Đèn Led", price: 17500, variance: "Đầu Dẹp", description: "Tua Vít Từ Tính Kiểm Tra Pha Đo Thông Mạch Kiểm Tra Dây Đứt Ngầm" },
  { id: 310, name: "Bút Thử Điện Cảm Ứng Thông Minh 2 Đèn Led", price: 17500, variance: "Đầu 4 Cạnh", description: "Tua Vít Từ Tính Kiểm Tra Pha Đo Thông Mạch Kiểm Tra Dây Đứt Ngầm" },
  { id: 311, name: "Camera Tapo Wi-Fi Trong Nhà TP-LINK C212 2K 3MP", price: 690000, variance: "", description: "Phát Hiện Chuyển Động Báo Động Âm Thanh Ánh Sáng Điều Khiển Giọng Nói" },
  { id: 312, name: "Ổ Cắm Thông Minh WiFi Lumi 3000W", price: 739000, variance: "Combo 3 Ổ Lumi", description: "Điều Khiển Từ Xa Đo Điện Hoạt Động Khi Không Có WiFi An Toàn Tiết Kiệm" },
  { id: 313, name: "Ổ Cắm Thông Minh WiFi Lumi 3000W", price: 269000, variance: "Ổ Cắm Lumi", description: "Điều Khiển Từ Xa Đo Điện Hoạt Động Khi Không Có WiFi An Toàn Tiết Kiệm" },
  { id: 314, name: "Ổ Cắm Thông Minh WiFi Lumi 3000W", price: 509000, variance: "Combo 2 Ổ Lumi", description: "Điều Khiển Từ Xa Đo Điện Hoạt Động Khi Không Có WiFi An Toàn Tiết Kiệm" },
  { id: 315, name: "Camera Trông Trẻ 365 Selection PB1 2K", price: 1590000, variance: "", description: "Phát Hiện Chuyển Động Tiếng Khóc Tích Hợp Cảm Biến Nhiệt Độ Độ Ẩm Phát Nhạc Ru" },
  { id: 316, name: "Camera An Ninh WiFi TP-Link TAPO C225", price: 1499000, variance: "", description: "Camera AI 2K 4MP Theo Dõi Chuyển Động Cảm Biến Ánh Sáng Đàm Thoại 2 Chiều" },
  { id: 317, name: "Camera Ngoài Trời TP-LINK TAPO C510W 3MP", price: 1590000, variance: "", description: "Phát Hiện Người Có Màu Ban Đêm Báo Động Âm Thanh IP65 Chống Chịu Thời Tiết" },
  { id: 318, name: "Bóng Đèn Rọi Spotlight Thông Minh Tapo L630 RGB Chuôi GU10", price: 359000, variance: "", description: "Đa Sắc Hẹn Giờ Điều Khiển Giọng Nói Alexa Google Assist" },
  { id: 319, name: "Combo Công Tắc Cửa Cuốn Datic Kết Hợp Camera Icat Hunonic", price: 2169000, variance: "Camera Icat Indoor", description: "Đóng Mở Từ Xa Theo Dõi Camera Ngay Trên Giao Diện Đóng Mở" },
  { id: 320, name: "Combo Công Tắc Cửa Cuốn Datic Kết Hợp Camera Icat Hunonic", price: 2500000, variance: "Màu Trắng+Outdoor", description: "Đóng Mở Từ Xa Theo Dõi Camera Ngay Trên Giao Diện Đóng Mở" },
  { id: 321, name: "Combo Công Tắc Cửa Cuốn Datic Kết Hợp Camera Icat Hunonic", price: 1500000, variance: "Màu Đen+IcatMini", description: "Đóng Mở Từ Xa Theo Dõi Camera Ngay Trên Giao Diện Đóng Mở" },
  { id: 322, name: "Combo Công Tắc Cửa Cuốn Datic Kết Hợp Camera Icat Hunonic", price: 2000000, variance: "Màu Trắng+Indoor", description: "Đóng Mở Từ Xa Theo Dõi Camera Ngay Trên Giao Diện Đóng Mở" },
  { id: 323, name: "Combo Công Tắc Cửa Cuốn Datic Kết Hợp Camera Icat Hunonic", price: 1500000, variance: "Màu Trắng+IcatMIni", description: "Đóng Mở Từ Xa Theo Dõi Camera Ngay Trên Giao Diện Đóng Mở" },
  { id: 324, name: "Combo Công Tắc Cửa Cuốn Datic Kết Hợp Camera Icat Hunonic", price: 2000000, variance: "Màu Đen+Indoor", description: "Đóng Mở Từ Xa Theo Dõi Camera Ngay Trên Giao Diện Đóng Mở" },
  { id: 325, name: "Combo Công Tắc Cửa Cuốn Datic Kết Hợp Camera Icat Hunonic", price: 2500000, variance: "Màu Đen+Outdoor", description: "Đóng Mở Từ Xa Theo Dõi Camera Ngay Trên Giao Diện Đóng Mở" },
  { id: 326, name: "Camera WiFi Thông Minh Hunonic ICat Mini 1080P", price: 1048000, variance: "Kèm Thẻ Lexar 32G", description: "Xoay 360 Độ Theo Dõi Chuyển Động Đàm Thoại 2 Chiều Tích Hợp Ngữ Cảnh" },
  { id: 327, name: "Camera WiFi Thông Minh Hunonic ICat Mini 1080P", price: 1098000, variance: "Kèm Thẻ Lexar 64G", description: "Xoay 360 Độ Theo Dõi Chuyển Động Đàm Thoại 2 Chiều Tích Hợp Ngữ Cảnh" },
  { id: 328, name: "Camera WiFi Thông Minh Hunonic ICat Mini 1080P", price: 939000, variance: "Chỉ Camera", description: "Xoay 360 Độ Theo Dõi Chuyển Động Đàm Thoại 2 Chiều Tích Hợp Ngữ Cảnh" },
  { id: 329, name: "Kìm Tuốt Dây Thợ Điện Đa Năng", price: 80000, variance: "", description: "Dụng Cụ Cắt Dây Uốn Dây Thép Gió HSS Lò Xo Ẩn" },
  { id: 330, name: "Ổ Cắm Thông Minh Tròn WiFi 16A", price: 490000, variance: "12 Tháng", description: "Hẹn Giờ Bật Tắt Từ Xa Đo Điện Năng Tiêu Thụ Điều Khiển Giọng Nói" },
  { id: 331, name: "Ổ Cắm Thông Minh Tròn WiFi 16A", price: 319000, variance: "1 Tháng", description: "Hẹn Giờ Bật Tắt Từ Xa Đo Điện Năng Tiêu Thụ Điều Khiển Giọng Nói" },
  { id: 332, name: "Camera Wifi ICat Indoor Hunonic Full HD", price: 2169000, variance: "", description: "Quay 355 độ Giám Sát Trực Tiếp Từ Xa Tích hợp Mic và Loa Hồng Ngoại Ban Đêm" },
  { id: 333, name: "Camera Ngoài Trời 2 Mắt IMOU Cruiser Dual 3MP+3MP", price: 1999000, variance: "", description: "Chống Ngược Sáng Phát Hiện Âm Thanh Chuyển Động Tích Hợp Còi Đèn" },
  { id: 334, name: "Đui Đèn Chui Đèn E27", price: 7000, variance: "Đui Treo Màu Trắng", description: "Đui Đèn Xoáy Treo Lò Xo Kín Nước Gắn Tường 45độ 90độ Chống Cháy Chống Vỡ Trang Trí" },
  { id: 335, name: "Đui Đèn Chui Đèn E27", price: 9000, variance: "Đui 90 Độ", description: "Đui Đèn Xoáy Treo Lò Xo Kín Nước Gắn Tường 45độ 90độ Chống Cháy Chống Vỡ Trang Trí" },
  { id: 336, name: "Đui Đèn Chui Đèn E27", price: 7000, variance: "Đui Treo Màu Đen", description: "Đui Đèn Xoáy Treo Lò Xo Kín Nước Gắn Tường 45độ 90độ Chống Cháy Chống Vỡ Trang Trí" },
  { id: 337, name: "Đui Đèn Chui Đèn E27", price: 13000, variance: "Đui Trắng + Dây 12cm", description: "Đui Đèn Xoáy Treo Lò Xo Kín Nước Gắn Tường 45độ 90độ Chống Cháy Chống Vỡ Trang Trí" },
  { id: 338, name: "Đui Đèn Chui Đèn E27", price: 9000, variance: "Đui 45 Độ", description: "Đui Đèn Xoáy Treo Lò Xo Kín Nước Gắn Tường 45độ 90độ Chống Cháy Chống Vỡ Trang Trí" },
  { id: 339, name: "Bộ Điều Khiển Cổng Gate Hunonic WiFi/Bluetooth", price: 1850000, variance: "", description: "Điều Khiển Cổng Từ Xa Qua Điện Thoại Chia Sẻ Cho Gia Đình Cùng Sử Dụng" },
  { id: 340, name: "Camera 2 Mắt Ezviz H7c Dual 4MP+4MP", price: 1290000, variance: "", description: "Bao Quát Toàn Không Gian,Theo Dõi Chuyển Động Có Màu Ban Đêm Điều Khiển Giọng Nói" },
  { id: 341, name: "Bộ Đèn Led Dây Thông Minh Wi-Fi TP-Link Tapo L900-5", price: 799000, variance: "", description: "Điều Chỉnh Màu Sắc Hẹn Giờ Bật Tắt Nháy Theo Nhạc Tuổi Thọ Dài" },
];

  return (
    <div className={styles.wrapper}>
      <h2 className={sectionStyles.word}>Danh Sách Sản Phẩm</h2>
      <h4>🌟Dưới đây là các sản phẩm của cửa hàng. Bạn có thể nhờ Agent tư vấn lựa chọn hoặc tiến hành đặt hàng ngay.</h4>
      <table className={styles.table}>
        <thead>
          <tr>
            <th>STT</th>
            <th>Tên sản phẩm</th>
            <th>Mô tả sản phẩm</th>
            <th>Loại</th>
            <th>Giá sản phẩm</th>
          </tr>
        </thead>
        <tbody>
          {data.map((p) => (
            <tr key={p.id}>
              <td>{p.id}</td>
              <td>{p.name}</td>
              <td>{p.description}</td>
              <td>{p.variance}</td>
              <td>{p.price}</td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
};

export default Products;